export interface City {
  name: string;
  zipCodes?: string[];
}

export interface Province {
  name: string;
  cities: City[];
}

export const philippinesLocations: Province[] = [
  // LUZON
  // National Capital Region (NCR)
  {
    name: "Metro Manila",
    cities: [
      { name: "Caloocan", zipCodes: ["1400"] },
      { name: "Las Piñas", zipCodes: ["1740"] },
      { name: "Makati", zipCodes: ["1200"] },
      { name: "Malabon", zipCodes: ["1470"] },
      { name: "Mandaluyong", zipCodes: ["1550"] },
      { name: "Manila", zipCodes: ["1000"] },
      { name: "Marikina", zipCodes: ["1800"] },
      { name: "Muntinlupa", zipCodes: ["1770"] },
      { name: "Navotas", zipCodes: ["1485"] },
      { name: "Parañaque", zipCodes: ["1700"] },
      { name: "Pasay", zipCodes: ["1300"] },
      { name: "Pasig", zipCodes: ["1600"] },
      { name: "Pateros", zipCodes: ["1620"] },
      { name: "Quezon City", zipCodes: ["1100"] },
      { name: "San Juan", zipCodes: ["1500"] },
      { name: "Taguig", zipCodes: ["1630"] },
      { name: "Valenzuela", zipCodes: ["1440"] }
    ]
  },

  // Cordillera Administrative Region (CAR)
  {
    name: "Abra",
    cities: [
      { name: "Bangued", zipCodes: ["2800"] },
      { name: "Boliney", zipCodes: ["2807"] },
      { name: "Bucay", zipCodes: ["2801"] },
      { name: "Bucloc", zipCodes: ["2823"] },
      { name: "Daguioman", zipCodes: ["2806"] },
      { name: "Danglas", zipCodes: ["2818"] },
      { name: "Dolores", zipCodes: ["2804"] },
      { name: "La Paz", zipCodes: ["2822"] },
      { name: "Lacub", zipCodes: ["2819"] },
      { name: "Lagangilang", zipCodes: ["2805"] },
      { name: "Lagayan", zipCodes: ["2821"] },
      { name: "Langiden", zipCodes: ["2820"] },
      { name: "Licuan-Baay", zipCodes: ["2814"] },
      { name: "Luba", zipCodes: ["2803"] },
      { name: "Malibcong", zipCodes: ["2815"] },
      { name: "Manabo", zipCodes: ["2816"] },
      { name: "Peñarrubia", zipCodes: ["2802"] },
      { name: "Pidigan", zipCodes: ["2809"] },
      { name: "Pilar", zipCodes: ["2808"] },
      { name: "Sallapadan", zipCodes: ["2817"] },
      { name: "San Isidro", zipCodes: ["2811"] },
      { name: "San Juan", zipCodes: ["2810"] },
      { name: "San Quintin", zipCodes: ["2812"] },
      { name: "Tayum", zipCodes: ["2813"] },
      { name: "Tineg", zipCodes: ["2824"] },
      { name: "Tubo", zipCodes: ["2825"] },
      { name: "Villaviciosa", zipCodes: ["2826"] }
    ]
  },
  {
    name: "Apayao",
    cities: [
      { name: "Calanasan", zipCodes: ["3811"] },
      { name: "Conner", zipCodes: ["3800"] },
      { name: "Flora", zipCodes: ["3809"] },
      { name: "Kabugao", zipCodes: ["3800"] },
      { name: "Luna", zipCodes: ["3810"] },
      { name: "Pudtol", zipCodes: ["3808"] },
      { name: "Santa Marcela", zipCodes: ["3812"] }
    ]
  },
  {
    name: "Benguet",
    cities: [
      { name: "Baguio City", zipCodes: ["2600"] },
      { name: "Atok", zipCodes: ["2611"] },
      { name: "Bakun", zipCodes: ["2610"] },
      { name: "Bokod", zipCodes: ["2606"] },
      { name: "Buguias", zipCodes: ["2609"] },
      { name: "Itogon", zipCodes: ["2604"] },
      { name: "Kabayan", zipCodes: ["2608"] },
      { name: "Kapangan", zipCodes: ["2607"] },
      { name: "Kibungan", zipCodes: ["2612"] },
      { name: "La Trinidad", zipCodes: ["2601"] },
      { name: "Mankayan", zipCodes: ["2605"] },
      { name: "Sablan", zipCodes: ["2602"] },
      { name: "Tuba", zipCodes: ["2603"] },
      { name: "Tublay", zipCodes: ["2613"] }
    ]
  },
  {
    name: "Ifugao",
    cities: [
      { name: "Lagawe", zipCodes: ["3600"] },
      { name: "Aguinaldo", zipCodes: ["3604"] },
      { name: "Alfonso Lista", zipCodes: ["3611"] },
      { name: "Asipulo", zipCodes: ["3606"] },
      { name: "Banaue", zipCodes: ["3601"] },
      { name: "Hingyon", zipCodes: ["3608"] },
      { name: "Hungduan", zipCodes: ["3607"] },
      { name: "Kiangan", zipCodes: ["3605"] },
      { name: "Lamut", zipCodes: ["3602"] },
      { name: "Mayoyao", zipCodes: ["3609"] },
      { name: "Tinoc", zipCodes: ["3603"] }
    ]
  },
  {
    name: "Kalinga",
    cities: [
      { name: "Tabuk City", zipCodes: ["3800"] },
      { name: "Balbalan", zipCodes: ["3807"] },
      { name: "Lubuagan", zipCodes: ["3803"] },
      { name: "Pasil", zipCodes: ["3804"] },
      { name: "Pinukpuk", zipCodes: ["3801"] },
      { name: "Rizal", zipCodes: ["3806"] },
      { name: "Tanudan", zipCodes: ["3805"] },
      { name: "Tinglayan", zipCodes: ["3802"] }
    ]
  },
  {
    name: "Mountain Province",
    cities: [
      { name: "Bontoc", zipCodes: ["2616"] },
      { name: "Bauko", zipCodes: ["2620"] },
      { name: "Besao", zipCodes: ["2619"] },
      { name: "Natonin", zipCodes: ["2623"] },
      { name: "Paracelis", zipCodes: ["2624"] },
      { name: "Sabangan", zipCodes: ["2618"] },
      { name: "Sadanga", zipCodes: ["2621"] },
      { name: "Sagada", zipCodes: ["2617"] },
      { name: "Tadian", zipCodes: ["2615"] },
      { name: "Barlig", zipCodes: ["2622"] }
    ]
  },

  // Region I (Ilocos Region)
  {
    name: "Ilocos Norte",
    cities: [
      { name: "Laoag City", zipCodes: ["2900"] },
      { name: "Adams", zipCodes: ["2919"] },
      { name: "Bacarra", zipCodes: ["2913"] },
      { name: "Badoc", zipCodes: ["2904"] },
      { name: "Bangui", zipCodes: ["2917"] },
      { name: "Banna", zipCodes: ["2908"] },
      { name: "Batac City", zipCodes: ["2906"] },
      { name: "Burgos", zipCodes: ["2918"] },
      { name: "Carasi", zipCodes: ["2922"] },
      { name: "Currimao", zipCodes: ["2903"] },
      { name: "Dingras", zipCodes: ["2913"] },
      { name: "Dumalneg", zipCodes: ["2920"] },
      { name: "Marcos", zipCodes: ["2921"] },
      { name: "Nueva Era", zipCodes: ["2909"] },
      { name: "Pagudpud", zipCodes: ["2919"] },
      { name: "Paoay", zipCodes: ["2902"] },
      { name: "Pasuquin", zipCodes: ["2916"] },
      { name: "Piddig", zipCodes: ["2907"] },
      { name: "Pinili", zipCodes: ["2905"] },
      { name: "San Nicolas", zipCodes: ["2901"] },
      { name: "Sarrat", zipCodes: ["2914"] },
      { name: "Solsona", zipCodes: ["2915"] },
      { name: "Vintar", zipCodes: ["2911"] }
    ]
  },
  {
    name: "Ilocos Sur",
    cities: [
      { name: "Vigan City", zipCodes: ["2700"] },
      { name: "Candon City", zipCodes: ["2710"] },
      { name: "Alilem", zipCodes: ["2729"] },
      { name: "Banayoyo", zipCodes: ["2708"] },
      { name: "Bantay", zipCodes: ["2727"] },
      { name: "Burgos", zipCodes: ["2724"] },
      { name: "Cabugao", zipCodes: ["2732"] },
      { name: "Caoayan", zipCodes: ["2701"] },
      { name: "Cervantes", zipCodes: ["2718"] },
      { name: "Galimuyod", zipCodes: ["2717"] },
      { name: "Gregorio del Pilar", zipCodes: ["2719"] },
      { name: "Lidlidda", zipCodes: ["2716"] },
      { name: "Magsingal", zipCodes: ["2730"] },
      { name: "Nagbukel", zipCodes: ["2720"] },
      { name: "Narvacan", zipCodes: ["2704"] },
      { name: "Quirino", zipCodes: ["2721"] },
      { name: "Salcedo", zipCodes: ["2722"] },
      { name: "San Emilio", zipCodes: ["2723"] },
      { name: "San Esteban", zipCodes: ["2703"] },
      { name: "San Ildefonso", zipCodes: ["2728"] },
      { name: "San Juan", zipCodes: ["2726"] },
      { name: "San Vicente", zipCodes: ["2709"] },
      { name: "Santa", zipCodes: ["2705"] },
      { name: "Santa Catalina", zipCodes: ["2706"] },
      { name: "Santa Cruz", zipCodes: ["2713"] },
      { name: "Santa Lucia", zipCodes: ["2707"] },
      { name: "Santa Maria", zipCodes: ["2731"] },
      { name: "Santiago", zipCodes: ["2711"] },
      { name: "Santo Domingo", zipCodes: ["2712"] },
      { name: "Sigay", zipCodes: ["2725"] },
      { name: "Sinait", zipCodes: ["2733"] },
      { name: "Sugpon", zipCodes: ["2714"] },
      { name: "Suyo", zipCodes: ["2715"] },
      { name: "Tagudin", zipCodes: ["2702"] }
    ]
  },
  {
    name: "La Union",
    cities: [
      { name: "San Fernando City", zipCodes: ["2500"] },
      { name: "Agoo", zipCodes: ["2504"] },
      { name: "Aringay", zipCodes: ["2506"] },
      { name: "Bacnotan", zipCodes: ["2515"] },
      { name: "Bagulin", zipCodes: ["2514"] },
      { name: "Balaoan", zipCodes: ["2516"] },
      { name: "Bangar", zipCodes: ["2517"] },
      { name: "Bauang", zipCodes: ["2501"] },
      { name: "Burgos", zipCodes: ["2518"] },
      { name: "Caba", zipCodes: ["2502"] },
      { name: "Luna", zipCodes: ["2519"] },
      { name: "Naguilian", zipCodes: ["2503"] },
      { name: "Pugo", zipCodes: ["2513"] },
      { name: "Rosario", zipCodes: ["2507"] },
      { name: "San Gabriel", zipCodes: ["2520"] },
      { name: "San Juan", zipCodes: ["2514"] },
      { name: "Santo Tomas", zipCodes: ["2505"] },
      { name: "Santol", zipCodes: ["2521"] },
      { name: "Sudipen", zipCodes: ["2522"] },
      { name: "Tubao", zipCodes: ["2508"] }
    ]
  },
  {
    name: "Pangasinan",
    cities: [
      { name: "Dagupan City", zipCodes: ["2400"] },
      { name: "Alaminos City", zipCodes: ["2404"] },
      { name: "San Carlos City", zipCodes: ["2420"] },
      { name: "Urdaneta City", zipCodes: ["2428"] },
      { name: "Agno", zipCodes: ["2408"] },
      { name: "Aguilar", zipCodes: ["2407"] },
      { name: "Alcala", zipCodes: ["2425"] },
      { name: "Anda", zipCodes: ["2405"] },
      { name: "Asingan", zipCodes: ["2439"] },
      { name: "Balungao", zipCodes: ["2442"] },
      { name: "Bani", zipCodes: ["2403"] },
      { name: "Basista", zipCodes: ["2421"] },
      { name: "Bautista", zipCodes: ["2443"] },
      { name: "Bayambang", zipCodes: ["2423"] },
      { name: "Binalonan", zipCodes: ["2436"] },
      { name: "Binmaley", zipCodes: ["2417"] },
      { name: "Bolinao", zipCodes: ["2406"] },
      { name: "Bugallon", zipCodes: ["2418"] },
      { name: "Burgos", zipCodes: ["2410"] },
      { name: "Calasiao", zipCodes: ["2401"] },
      { name: "Dasol", zipCodes: ["2411"] },
      { name: "Infanta", zipCodes: ["2412"] },
      { name: "Labrador", zipCodes: ["2402"] },
      { name: "Laoac", zipCodes: ["2437"] },
      { name: "Lingayen", zipCodes: ["2401"] },
      { name: "Mabini", zipCodes: ["2413"] },
      { name: "Malasiqui", zipCodes: ["2421"] },
      { name: "Manaoag", zipCodes: ["2430"] },
      { name: "Mangaldan", zipCodes: ["2432"] },
      { name: "Mangatarem", zipCodes: ["2109"] },
      { name: "Mapandan", zipCodes: ["2429"] },
      { name: "Natividad", zipCodes: ["2440"] },
      { name: "Pozorrubio", zipCodes: ["2435"] },
      { name: "Rosales", zipCodes: ["2441"] },
      { name: "San Fabian", zipCodes: ["2433"] },
      { name: "San Jacinto", zipCodes: ["2434"] },
      { name: "San Manuel", zipCodes: ["2438"] },
      { name: "San Nicolas", zipCodes: ["2447"] },
      { name: "San Quintin", zipCodes: ["2448"] },
      { name: "Santa Barbara", zipCodes: ["2409"] },
      { name: "Santa Maria", zipCodes: ["2446"] },
      { name: "Santo Tomas", zipCodes: ["2445"] },
      { name: "Sison", zipCodes: ["2426"] },
      { name: "Sual", zipCodes: ["2414"] },
      { name: "Tayug", zipCodes: ["2444"] },
      { name: "Umingan", zipCodes: ["2108"] },
      { name: "Urbiztondo", zipCodes: ["2415"] },
      { name: "Villasis", zipCodes: ["2427"] }
    ]
  },

  // Region II (Cagayan Valley)
  {
    name: "Batanes",
    cities: [
      { name: "Basco", zipCodes: ["3900"] },
      { name: "Itbayat", zipCodes: ["3901"] },
      { name: "Ivana", zipCodes: ["3902"] },
      { name: "Mahatao", zipCodes: ["3903"] },
      { name: "Sabtang", zipCodes: ["3904"] },
      { name: "Uyugan", zipCodes: ["3905"] }
    ]
  },
  {
    name: "Cagayan",
    cities: [
      { name: "Tuguegarao City", zipCodes: ["3500"] },
      { name: "Abulug", zipCodes: ["3533"] },
      { name: "Alcala", zipCodes: ["3518"] },
      { name: "Allacapan", zipCodes: ["3532"] },
      { name: "Amulung", zipCodes: ["3514"] },
      { name: "Aparri", zipCodes: ["3515"] },
      { name: "Baggao", zipCodes: ["3505"] },
      { name: "Ballesteros", zipCodes: ["3531"] },
      { name: "Buguey", zipCodes: ["3517"] },
      { name: "Calayan", zipCodes: ["3516"] },
      { name: "Camalaniugan", zipCodes: ["3534"] },
      { name: "Claveria", zipCodes: ["3519"] },
      { name: "Enrile", zipCodes: ["3501"] },
      { name: "Gattaran", zipCodes: ["3506"] },
      { name: "Gonzaga", zipCodes: ["3516"] },
      { name: "Iguig", zipCodes: ["3503"] },
      { name: "Lal-lo", zipCodes: ["3535"] },
      { name: "Lasam", zipCodes: ["3507"] },
      { name: "Pamplona", zipCodes: ["3520"] },
      { name: "Peñablanca", zipCodes: ["3511"] },
      { name: "Piat", zipCodes: ["3504"] },
      { name: "Rizal", zipCodes: ["3513"] },
      { name: "Sanchez-Mira", zipCodes: ["3521"] },
      { name: "Santa Ana", zipCodes: ["3514"] },
      { name: "Santa Praxedes", zipCodes: ["3522"] },
      { name: "Santa Teresita", zipCodes: ["3523"] },
      { name: "Santo Niño", zipCodes: ["3524"] },
      { name: "Solana", zipCodes: ["3502"] },
      { name: "Tuao", zipCodes: ["3508"] }
    ]
  },
  {
    name: "Isabela",
    cities: [
      { name: "Ilagan City", zipCodes: ["3300"] },
      { name: "Cauayan City", zipCodes: ["3305"] },
      { name: "Santiago City", zipCodes: ["3311"] },
      { name: "Alicia", zipCodes: ["3306"] },
      { name: "Angadanan", zipCodes: ["3307"] },
      { name: "Aurora", zipCodes: ["3308"] },
      { name: "Benito Soliven", zipCodes: ["3309"] },
      { name: "Burgos", zipCodes: ["3310"] },
      { name: "Cabagan", zipCodes: ["3328"] },
      { name: "Cabatuan", zipCodes: ["3312"] },
      { name: "Cordon", zipCodes: ["3304"] },
      { name: "Delfin Albano", zipCodes: ["3313"] },
      { name: "Dinapigue", zipCodes: ["3314"] },
      { name: "Divilacan", zipCodes: ["3315"] },
      { name: "Echague", zipCodes: ["3309"] },
      { name: "Gamu", zipCodes: ["3316"] },
      { name: "Jones", zipCodes: ["3317"] },
      { name: "Luna", zipCodes: ["3318"] },
      { name: "Maconacon", zipCodes: ["3319"] },
      { name: "Mallig", zipCodes: ["3329"] },
      { name: "Naguilian", zipCodes: ["3320"] },
      { name: "Palanan", zipCodes: ["3321"] },
      { name: "Quezon", zipCodes: ["3322"] },
      { name: "Quirino", zipCodes: ["3323"] },
      { name: "Ramon", zipCodes: ["3324"] },
      { name: "Reina Mercedes", zipCodes: ["3303"] },
      { name: "Roxas", zipCodes: ["3301"] },
      { name: "San Agustin", zipCodes: ["3325"] },
      { name: "San Guillermo", zipCodes: ["3326"] },
      { name: "San Isidro", zipCodes: ["3327"] },
      { name: "San Manuel", zipCodes: ["3330"] },
      { name: "San Mariano", zipCodes: ["3331"] },
      { name: "San Mateo", zipCodes: ["3332"] },
      { name: "San Pablo", zipCodes: ["3333"] },
      { name: "Santa Maria", zipCodes: ["3334"] },
      { name: "Santo Tomas", zipCodes: ["3335"] },
      { name: "Tumauini", zipCodes: ["3302"] }
    ]
  },
  {
    name: "Nueva Vizcaya",
    cities: [
      { name: "Bayombong", zipCodes: ["3700"] },
      { name: "Alfonso Castañeda", zipCodes: ["3704"] },
      { name: "Ambaguio", zipCodes: ["3705"] },
      { name: "Aritao", zipCodes: ["3706"] },
      { name: "Bagabag", zipCodes: ["3711"] },
      { name: "Bambang", zipCodes: ["3701"] },
      { name: "Diadi", zipCodes: ["3707"] },
      { name: "Dupax del Norte", zipCodes: ["3708"] },
      { name: "Dupax del Sur", zipCodes: ["3709"] },
      { name: "Kasibu", zipCodes: ["3710"] },
      { name: "Kayapa", zipCodes: ["3712"] },
      { name: "Quezon", zipCodes: ["3713"] },
      { name: "Santa Fe", zipCodes: ["3714"] },
      { name: "Solano", zipCodes: ["3702"] },
      { name: "Villaverde", zipCodes: ["3703"] }
    ]
  },
  {
    name: "Quirino",
    cities: [
      { name: "Cabarroguis", zipCodes: ["3400"] },
      { name: "Aglipay", zipCodes: ["3401"] },
      { name: "Diffun", zipCodes: ["3402"] },
      { name: "Maddela", zipCodes: ["3403"] },
      { name: "Nagtipunan", zipCodes: ["3404"] },
      { name: "Saguday", zipCodes: ["3405"] }
    ]
  },

  // Region III (Central Luzon)
  {
    name: "Aurora",
    cities: [
      { name: "Baler", zipCodes: ["3200"] },
      { name: "Casiguran", zipCodes: ["3204"] },
      { name: "Dilasag", zipCodes: ["3205"] },
      { name: "Dinalungan", zipCodes: ["3203"] },
      { name: "Dingalan", zipCodes: ["3206"] },
      { name: "Dipaculao", zipCodes: ["3202"] },
      { name: "Maria Aurora", zipCodes: ["3207"] },
      { name: "San Luis", zipCodes: ["3201"] }
    ]
  },
  {
    name: "Bataan",
    cities: [
      { name: "Balanga City", zipCodes: ["2100"] },
      { name: "Abucay", zipCodes: ["2114"] },
      { name: "Bagac", zipCodes: ["2107"] },
      { name: "Dinalupihan", zipCodes: ["2110"] },
      { name: "Hermosa", zipCodes: ["2111"] },
      { name: "Limay", zipCodes: ["2103"] },
      { name: "Mariveles", zipCodes: ["2105"] },
      { name: "Morong", zipCodes: ["2106"] },
      { name: "Orani", zipCodes: ["2112"] },
      { name: "Orion", zipCodes: ["2113"] },
      { name: "Pilar", zipCodes: ["2101"] },
      { name: "Samal", zipCodes: ["2115"] }
    ]
  },
  {
    name: "Bulacan",
    cities: [
      { name: "Malolos City", zipCodes: ["3000"] },
      { name: "Meycauayan City", zipCodes: ["3020"] },
      { name: "San Jose del Monte City", zipCodes: ["3023"] },
      { name: "Angat", zipCodes: ["3017"] },
      { name: "Balagtas", zipCodes: ["3016"] },
      { name: "Baliuag", zipCodes: ["3006"] },
      { name: "Bocaue", zipCodes: ["3018"] },
      { name: "Bulakan", zipCodes: ["3017"] },
      { name: "Bustos", zipCodes: ["3007"] },
      { name: "Calumpit", zipCodes: ["3003"] },
      { name: "Doña Remedios Trinidad", zipCodes: ["3009"] },
      { name: "Guiguinto", zipCodes: ["3015"] },
      { name: "Hagonoy", zipCodes: ["3002"] },
      { name: "Marilao", zipCodes: ["3019"] },
      { name: "Norzagaray", zipCodes: ["3013"] },
      { name: "Obando", zipCodes: ["3021"] },
      { name: "Pandi", zipCodes: ["3014"] },
      { name: "Paombong", zipCodes: ["3001"] },
      { name: "Plaridel", zipCodes: ["3004"] },
      { name: "Pulilan", zipCodes: ["3005"] },
      { name: "San Ildefonso", zipCodes: ["3010"] },
      { name: "San Miguel", zipCodes: ["3011"] },
      { name: "San Rafael", zipCodes: ["3008"] },
      { name: "Santa Maria", zipCodes: ["3022"] }
    ]
  },
  {
    name: "Nueva Ecija",
    cities: [
      { name: "Palayan City", zipCodes: ["3132"] },
      { name: "Cabanatuan City", zipCodes: ["3100"] },
      { name: "Gapan City", zipCodes: ["3105"] },
      { name: "San Antonio", zipCodes: ["3103"] },
      { name: "San Jose City", zipCodes: ["3121"] },
      { name: "Science City of Muñoz", zipCodes: ["3120"] },
      { name: "Aliaga", zipCodes: ["3111"] },
      { name: "Bongabon", zipCodes: ["3128"] },
      { name: "Cabiao", zipCodes: ["3106"] },
      { name: "Carranglan", zipCodes: ["3139"] },
      { name: "Cuyapo", zipCodes: ["3117"] },
      { name: "Gabaldon", zipCodes: ["3131"] },
      { name: "General Mamerto Natividad", zipCodes: ["3129"] },
      { name: "General Tinio", zipCodes: ["3104"] },
      { name: "Guimba", zipCodes: ["3115"] },
      { name: "Jaen", zipCodes: ["3108"] },
      { name: "Laur", zipCodes: ["3130"] },
      { name: "Licab", zipCodes: ["3116"] },
      { name: "Llanera", zipCodes: ["3119"] },
      { name: "Lupao", zipCodes: ["3118"] },
      { name: "Nampicuan", zipCodes: ["3114"] },
      { name: "Pantabangan", zipCodes: ["3135"] },
      { name: "Peñaranda", zipCodes: ["3112"] },
      { name: "Quezon", zipCodes: ["3113"] },
      { name: "Rizal", zipCodes: ["3133"] },
      { name: "San Isidro", zipCodes: ["3107"] },
      { name: "San Leonardo", zipCodes: ["3102"] },
      { name: "Santa Rosa", zipCodes: ["3101"] },
      { name: "Santo Domingo", zipCodes: ["3134"] },
      { name: "Talavera", zipCodes: ["3109"] },
      { name: "Talugtug", zipCodes: ["3110"] },
      { name: "Zaragoza", zipCodes: ["3127"] }
    ]
  },
  {
    name: "Pampanga",
    cities: [
      { name: "San Fernando City", zipCodes: ["2000"] },
      { name: "Angeles City", zipCodes: ["2009"] },
      { name: "Mabalacat City", zipCodes: ["2010"] },
      { name: "Apalit", zipCodes: ["2016"] },
      { name: "Arayat", zipCodes: ["2012"] },
      { name: "Bacolor", zipCodes: ["2001"] },
      { name: "Candaba", zipCodes: ["2027"] },
      { name: "Floridablanca", zipCodes: ["2006"] },
      { name: "Guagua", zipCodes: ["2003"] },
      { name: "Lubao", zipCodes: ["2005"] },
      { name: "Macabebe", zipCodes: ["2018"] },
      { name: "Magalang", zipCodes: ["2011"] },
      { name: "Masantol", zipCodes: ["2017"] },
      { name: "Mexico", zipCodes: ["2021"] },
      { name: "Minalin", zipCodes: ["2019"] },
      { name: "Porac", zipCodes: ["2008"] },
      { name: "Sasmuan", zipCodes: ["2004"] },
      { name: "Santa Ana", zipCodes: ["2022"] },
      { name: "Santa Rita", zipCodes: ["2002"] },
      { name: "Santo Tomas", zipCodes: ["2020"] }
    ]
  },
  {
    name: "Tarlac",
    cities: [
      { name: "Tarlac City", zipCodes: ["2300"] },
      { name: "Anao", zipCodes: ["2311"] },
      { name: "Bamban", zipCodes: ["2317"] },
      { name: "Camiling", zipCodes: ["2306"] },
      { name: "Capas", zipCodes: ["2315"] },
      { name: "Concepcion", zipCodes: ["2316"] },
      { name: "Gerona", zipCodes: ["2301"] },
      { name: "La Paz", zipCodes: ["2314"] },
      { name: "Mayantoc", zipCodes: ["2304"] },
      { name: "Moncada", zipCodes: ["2308"] },
      { name: "Paniqui", zipCodes: ["2307"] },
      { name: "Pura", zipCodes: ["2313"] },
      { name: "Ramos", zipCodes: ["2309"] },
      { name: "San Clemente", zipCodes: ["2312"] },
      { name: "San Jose", zipCodes: ["2318"] },
      { name: "San Manuel", zipCodes: ["2310"] },
      { name: "Santa Ignacia", zipCodes: ["2305"] },
      { name: "Victoria", zipCodes: ["2303"] }
    ]
  },
  {
    name: "Zambales",
    cities: [
      { name: "Olongapo City", zipCodes: ["2200"] },
      { name: "Iba", zipCodes: ["2201"] },
      { name: "Botolan", zipCodes: ["2202"] },
      { name: "Cabangan", zipCodes: ["2203"] },
      { name: "Candelaria", zipCodes: ["2212"] },
      { name: "Castillejos", zipCodes: ["2208"] },
      { name: "Masinloc", zipCodes: ["2211"] },
      { name: "Palauig", zipCodes: ["2204"] },
      { name: "San Antonio", zipCodes: ["2206"] },
      { name: "San Felipe", zipCodes: ["2205"] },
      { name: "San Marcelino", zipCodes: ["2207"] },
      { name: "San Narciso", zipCodes: ["2209"] },
      { name: "Santa Cruz", zipCodes: ["2210"] },
      { name: "Subic", zipCodes: ["2222"] }
    ]
  },

  // Region IV-A (CALABARZON)
  {
    name: "Batangas",
    cities: [
      { name: "Batangas City", zipCodes: ["4200"] },
      { name: "Lipa City", zipCodes: ["4217"] },
      { name: "Tanauan City", zipCodes: ["4232"] },
      { name: "Santo Tomas City", zipCodes: ["4234"] },
      { name: "Agoncillo", zipCodes: ["4211"] },
      { name: "Alitagtag", zipCodes: ["4205"] },
      { name: "Balayan", zipCodes: ["4213"] },
      { name: "Balete", zipCodes: ["4219"] },
      { name: "Bauan", zipCodes: ["4201"] },
      { name: "Calaca", zipCodes: ["4212"] },
      { name: "Calatagan", zipCodes: ["4215"] },
      { name: "Cuenca", zipCodes: ["4222"] },
      { name: "Ibaan", zipCodes: ["4230"] },
      { name: "Laurel", zipCodes: ["4221"] },
      { name: "Lemery", zipCodes: ["4209"] },
      { name: "Lian", zipCodes: ["4216"] },
      { name: "Lobo", zipCodes: ["4207"] },
      { name: "Mabini", zipCodes: ["4202"] },
      { name: "Malvar", zipCodes: ["4233"] },
      { name: "Mataasnakahoy", zipCodes: ["4223"] },
      { name: "Nasugbu", zipCodes: ["4231"] },
      { name: "Padre Garcia", zipCodes: ["4224"] },
      { name: "Rosario", zipCodes: ["4225"] },
      { name: "San Jose", zipCodes: ["4227"] },
      { name: "San Juan", zipCodes: ["4226"] },
      { name: "San Luis", zipCodes: ["4208"] },
      { name: "San Nicolas", zipCodes: ["4214"] },
      { name: "San Pascual", zipCodes: ["4204"] },
      { name: "Santa Teresita", zipCodes: ["4210"] },
      { name: "Taal", zipCodes: ["4208"] },
      { name: "Talisay", zipCodes: ["4220"] },
      { name: "Taysan", zipCodes: ["4228"] },
      { name: "Tingloy", zipCodes: ["4206"] },
      { name: "Tuy", zipCodes: ["4203"] }
    ]
  },
  {
    name: "Cavite",
    cities: [
      { name: "Trece Martires City", zipCodes: ["4109"] },
      { name: "Cavite City", zipCodes: ["4100"] },
      { name: "Dasmariñas City", zipCodes: ["4114"] },
      { name: "Bacoor City", zipCodes: ["4102"] },
      { name: "Imus City", zipCodes: ["4103"] },
      { name: "General Trias City", zipCodes: ["4107"] },
      { name: "Tagaytay City", zipCodes: ["4120"] },
      { name: "Alfonso", zipCodes: ["4123"] },
      { name: "Amadeo", zipCodes: ["4119"] },
      { name: "Carmona", zipCodes: ["4116"] },
      { name: "General Emilio Aguinaldo", zipCodes: ["4124"] },
      { name: "General Mariano Alvarez", zipCodes: ["4117"] },
      { name: "Indang", zipCodes: ["4122"] },
      { name: "Kawit", zipCodes: ["4104"] },
      { name: "Magallanes", zipCodes: ["4113"] },
      { name: "Maragondon", zipCodes: ["4112"] },
      { name: "Mendez", zipCodes: ["4121"] },
      { name: "Naic", zipCodes: ["4110"] },
      { name: "Noveleta", zipCodes: ["4105"] },
      { name: "Rosario", zipCodes: ["4106"] },
      { name: "Silang", zipCodes: ["4118"] },
      { name: "Tanza", zipCodes: ["4108"] },
      { name: "Ternate", zipCodes: ["4111"] }
    ]
  },
  {
    name: "Laguna",
    cities: [
      { name: "Santa Rosa City", zipCodes: ["4026"] },
      { name: "Calamba City", zipCodes: ["4027"] },
      { name: "Biñan City", zipCodes: ["4024"] },
      { name: "San Pedro City", zipCodes: ["4023"] },
      { name: "San Pablo City", zipCodes: ["4000"] },
      { name: "Cabuyao City", zipCodes: ["4025"] },
      { name: "Alaminos", zipCodes: ["4001"] },
      { name: "Bay", zipCodes: ["4033"] },
      { name: "Calauan", zipCodes: ["4028"] },
      { name: "Cavinti", zipCodes: ["4012"] },
      { name: "Famy", zipCodes: ["4017"] },
      { name: "Kalayaan", zipCodes: ["4004"] },
      { name: "Liliw", zipCodes: ["4004"] },
      { name: "Los Baños", zipCodes: ["4030"] },
      { name: "Luisiana", zipCodes: ["4016"] },
      { name: "Lumban", zipCodes: ["4014"] },
      { name: "Mabitac", zipCodes: ["4013"] },
      { name: "Magdalena", zipCodes: ["4007"] },
      { name: "Majayjay", zipCodes: ["4005"] },
      { name: "Nagcarlan", zipCodes: ["4002"] },
      { name: "Paete", zipCodes: ["4015"] },
      { name: "Pagsanjan", zipCodes: ["4008"] },
      { name: "Pakil", zipCodes: ["4018"] },
      { name: "Pangil", zipCodes: ["4019"] },
      { name: "Pila", zipCodes: ["4010"] },
      { name: "Rizal", zipCodes: ["4009"] },
      { name: "San Antonio", zipCodes: ["4029"] },
      { name: "Santa Cruz", zipCodes: ["4009"] },
      { name: "Santa Maria", zipCodes: ["4022"] },
      { name: "Siniloan", zipCodes: ["4021"] },
      { name: "Victoria", zipCodes: ["4020"] }
    ]
  },
  {
    name: "Quezon",
    cities: [
      { name: "Lucena City", zipCodes: ["4301"] },
      { name: "Tayabas City", zipCodes: ["4327"] },
      { name: "Agdangan", zipCodes: ["4304"] },
      { name: "Alabat", zipCodes: ["4333"] },
      { name: "Atimonan", zipCodes: ["4331"] },
      { name: "Buenavista", zipCodes: ["4320"] },
      { name: "Burdeos", zipCodes: ["4340"] },
      { name: "Calauag", zipCodes: ["4318"] },
      { name: "Candelaria", zipCodes: ["4323"] },
      { name: "Catanauan", zipCodes: ["4311"] },
      { name: "Dolores", zipCodes: ["4326"] },
      { name: "General Luna", zipCodes: ["4307"] },
      { name: "General Nakar", zipCodes: ["4338"] },
      { name: "Guinayangan", zipCodes: ["4319"] },
      { name: "Gumaca", zipCodes: ["4307"] },
      { name: "Infanta", zipCodes: ["4336"] },
      { name: "Jomalig", zipCodes: ["4335"] },
      { name: "Lopez", zipCodes: ["4316"] },
      { name: "Lucban", zipCodes: ["4328"] },
      { name: "Macalelon", zipCodes: ["4310"] },
      { name: "Mauban", zipCodes: ["4330"] },
      { name: "Mulanay", zipCodes: ["4312"] },
      { name: "Padre Burgos", zipCodes: ["4303"] },
      { name: "Pagbilao", zipCodes: ["4302"] },
      { name: "Panukulan", zipCodes: ["4337"] },
      { name: "Patnanungan", zipCodes: ["4334"] },
      { name: "Perez", zipCodes: ["4332"] },
      { name: "Pitogo", zipCodes: ["4308"] },
      { name: "Plaridel", zipCodes: ["4306"] },
      { name: "Polillo", zipCodes: ["4315"] },
      { name: "Quezon", zipCodes: ["4339"] },
      { name: "Real", zipCodes: ["4335"] },
      { name: "Sampaloc", zipCodes: ["4329"] },
      { name: "San Andres", zipCodes: ["4313"] },
      { name: "San Antonio", zipCodes: ["4324"] },
      { name: "San Francisco", zipCodes: ["4314"] },
      { name: "San Narciso", zipCodes: ["4309"] },
      { name: "Sariaya", zipCodes: ["4322"] },
      { name: "Tagkawayan", zipCodes: ["4321"] },
      { name: "Tiaong", zipCodes: ["4325"] },
      { name: "Unisan", zipCodes: ["4305"] }
    ]
  },
  {
    name: "Rizal",
    cities: [
      { name: "Antipolo City", zipCodes: ["1870"] },
      { name: "Angono", zipCodes: ["1930"] },
      { name: "Baras", zipCodes: ["1970"] },
      { name: "Binangonan", zipCodes: ["1940"] },
      { name: "Cainta", zipCodes: ["1900"] },
      { name: "Cardona", zipCodes: ["1950"] },
      { name: "Jalajala", zipCodes: ["1960"] },
      { name: "Morong", zipCodes: ["1980"] },
      { name: "Pililla", zipCodes: ["1910"] },
      { name: "Rodriguez", zipCodes: ["1860"] },
      { name: "San Mateo", zipCodes: ["1850"] },
      { name: "Tanay", zipCodes: ["1980"] },
      { name: "Taytay", zipCodes: ["1920"] },
      { name: "Teresa", zipCodes: ["1880"] }
    ]
  },

  // Region IV-B (MIMAROPA)
  {
    name: "Marinduque",
    cities: [
      { name: "Boac", zipCodes: ["4900"] },
      { name: "Buenavista", zipCodes: ["4904"] },
      { name: "Gasan", zipCodes: ["4905"] },
      { name: "Mogpog", zipCodes: ["4901"] },
      { name: "Santa Cruz", zipCodes: ["4902"] },
      { name: "Torrijos", zipCodes: ["4903"] }
    ]
  },
  {
    name: "Occidental Mindoro",
    cities: [
      { name: "Mamburao", zipCodes: ["5100"] },
      { name: "Abra de Ilog", zipCodes: ["5103"] },
      { name: "Calintaan", zipCodes: ["5104"] },
      { name: "Looc", zipCodes: ["5105"] },
      { name: "Lubang", zipCodes: ["5109"] },
      { name: "Magsaysay", zipCodes: ["5106"] },
      { name: "Paluan", zipCodes: ["5102"] },
      { name: "Rizal", zipCodes: ["5107"] },
      { name: "Sablayan", zipCodes: ["5101"] },
      { name: "San Jose", zipCodes: ["5108"] },
      { name: "Santa Cruz", zipCodes: ["5110"] }
    ]
  },
  {
    name: "Oriental Mindoro",
    cities: [
      { name: "Calapan City", zipCodes: ["5200"] },
      { name: "Baco", zipCodes: ["5201"] },
      { name: "Bansud", zipCodes: ["5210"] },
      { name: "Bongabong", zipCodes: ["5207"] },
      { name: "Bulalacao", zipCodes: ["5212"] },
      { name: "Gloria", zipCodes: ["5208"] },
      { name: "Mansalay", zipCodes: ["5211"] },
      { name: "Naujan", zipCodes: ["5203"] },
      { name: "Pinamalayan", zipCodes: ["5209"] },
      { name: "Pola", zipCodes: ["5204"] },
      { name: "Puerto Galera", zipCodes: ["5202"] },
      { name: "Roxas", zipCodes: ["5213"] },
      { name: "San Teodoro", zipCodes: ["5205"] },
      { name: "Socorro", zipCodes: ["5206"] },
      { name: "Victoria", zipCodes: ["5214"] }
    ]
  },
  {
    name: "Palawan",
    cities: [
      { name: "Puerto Princesa City", zipCodes: ["5300"] },
      { name: "Aborlan", zipCodes: ["5302"] },
      { name: "Agutaya", zipCodes: ["5318"] },
      { name: "Araceli", zipCodes: ["5319"] },
      { name: "Balabac", zipCodes: ["5307"] },
      { name: "Bataraza", zipCodes: ["5306"] },
      { name: "Brooke's Point", zipCodes: ["5305"] },
      { name: "Busuanga", zipCodes: ["5316"] },
      { name: "Cagayancillo", zipCodes: ["5320"] },
      { name: "Coron", zipCodes: ["5317"] },
      { name: "Culion", zipCodes: ["5315"] },
      { name: "Cuyo", zipCodes: ["5321"] },
      { name: "Dumaran", zipCodes: ["5322"] },
      { name: "El Nido", zipCodes: ["5313"] },
      { name: "Kalayaan", zipCodes: ["5323"] },
      { name: "Linapacan", zipCodes: ["5314"] },
      { name: "Magsaysay", zipCodes: ["5324"] },
      { name: "Narra", zipCodes: ["5303"] },
      { name: "Quezon", zipCodes: ["5304"] },
      { name: "Rizal", zipCodes: ["5301"] },
      { name: "Roxas", zipCodes: ["5308"] },
      { name: "San Vicente", zipCodes: ["5309"] },
      { name: "Sofronio Española", zipCodes: ["5310"] },
      { name: "Taytay", zipCodes: ["5312"] }
    ]
  },
  {
    name: "Romblon",
    cities: [
      { name: "Romblon", zipCodes: ["5500"] },
      { name: "Alcantara", zipCodes: ["5501"] },
      { name: "Banton", zipCodes: ["5507"] },
      { name: "Cajidiocan", zipCodes: ["5506"] },
      { name: "Calatrava", zipCodes: ["5508"] },
      { name: "Concepcion", zipCodes: ["5509"] },
      { name: "Corcuera", zipCodes: ["5510"] },
      { name: "Ferrol", zipCodes: ["5502"] },
      { name: "Looc", zipCodes: ["5503"] },
      { name: "Magdiwang", zipCodes: ["5505"] },
      { name: "Odiongan", zipCodes: ["5511"] },
      { name: "San Agustin", zipCodes: ["5512"] },
      { name: "San Andres", zipCodes: ["5513"] },
      { name: "San Fernando", zipCodes: ["5514"] },
      { name: "San Jose", zipCodes: ["5515"] },
      { name: "Santa Fe", zipCodes: ["5516"] },
      { name: "Santa Maria", zipCodes: ["5504"] }
    ]
  },

  // Region V (Bicol Region)
  {
    name: "Albay",
    cities: [
      { name: "Legazpi City", zipCodes: ["4500"] },
      { name: "Ligao City", zipCodes: ["4504"] },
      { name: "Tabaco City", zipCodes: ["4511"] },
      { name: "Bacacay", zipCodes: ["4503"] },
      { name: "Camalig", zipCodes: ["4502"] },
      { name: "Daraga", zipCodes: ["4501"] },
      { name: "Guinobatan", zipCodes: ["4506"] },
      { name: "Jovellar", zipCodes: ["4507"] },
      { name: "Libon", zipCodes: ["4505"] },
      { name: "Malilipot", zipCodes: ["4508"] },
      { name: "Malinao", zipCodes: ["4509"] },
      { name: "Manito", zipCodes: ["4510"] },
      { name: "Oas", zipCodes: ["4513"] },
      { name: "Pio Duran", zipCodes: ["4514"] },
      { name: "Polangui", zipCodes: ["4512"] },
      { name: "Rapu-Rapu", zipCodes: ["4516"] },
      { name: "Santo Domingo", zipCodes: ["4517"] },
      { name: "Tiwi", zipCodes: ["4515"] }
    ]
  },
  {
    name: "Camarines Norte",
    cities: [
      { name: "Daet", zipCodes: ["4600"] },
      { name: "Basud", zipCodes: ["4601"] },
      { name: "Capalonga", zipCodes: ["4608"] },
      { name: "Jose Panganiban", zipCodes: ["4606"] },
      { name: "Labo", zipCodes: ["4604"] },
      { name: "Mercedes", zipCodes: ["4602"] },
      { name: "Paracale", zipCodes: ["4605"] },
      { name: "San Lorenzo Ruiz", zipCodes: ["4609"] },
      { name: "San Vicente", zipCodes: ["4610"] },
      { name: "Santa Elena", zipCodes: ["4611"] },
      { name: "Talisay", zipCodes: ["4607"] },
      { name: "Vinzons", zipCodes: ["4603"] }
    ]
  },
  {
    name: "Camarines Sur",
    cities: [
      { name: "Naga City", zipCodes: ["4400"] },
      { name: "Iriga City", zipCodes: ["4431"] },
      { name: "Baao", zipCodes: ["4432"] },
      { name: "Balatan", zipCodes: ["4433"] },
      { name: "Bato", zipCodes: ["4434"] },
      { name: "Bombon", zipCodes: ["4407"] },
      { name: "Buhi", zipCodes: ["4430"] },
      { name: "Bula", zipCodes: ["4408"] },
      { name: "Cabusao", zipCodes: ["4409"] },
      { name: "Calabanga", zipCodes: ["4410"] },
      { name: "Camaligan", zipCodes: ["4401"] },
      { name: "Canaman", zipCodes: ["4402"] },
      { name: "Caramoan", zipCodes: ["4429"] },
      { name: "Del Gallego", zipCodes: ["4411"] },
      { name: "Gainza", zipCodes: ["4403"] },
      { name: "Garchitorena", zipCodes: ["4426"] },
      { name: "Goa", zipCodes: ["4422"] },
      { name: "Lagonoy", zipCodes: ["4425"] },
      { name: "Libmanan", zipCodes: ["4412"] },
      { name: "Lupi", zipCodes: ["4413"] },
      { name: "Magarao", zipCodes: ["4404"] },
      { name: "Milaor", zipCodes: ["4405"] },
      { name: "Minalabac", zipCodes: ["4406"] },
      { name: "Nabua", zipCodes: ["4434"] },
      { name: "Ocampo", zipCodes: ["4435"] },
      { name: "Pamplona", zipCodes: ["4414"] },
      { name: "Pasacao", zipCodes: ["4415"] },
      { name: "Pili", zipCodes: ["4418"] },
      { name: "Presentacion", zipCodes: ["4427"] },
      { name: "Ragay", zipCodes: ["4416"] },
      { name: "Sagñay", zipCodes: ["4420"] },
      { name: "San Fernando", zipCodes: ["4428"] },
      { name: "San Jose", zipCodes: ["4423"] },
      { name: "Sipocot", zipCodes: ["4417"] },
      { name: "Siruma", zipCodes: ["4424"] },
      { name: "Tigaon", zipCodes: ["4421"] },
      { name: "Tinambac", zipCodes: ["4419"] }
    ]
  },
  {
    name: "Catanduanes",
    cities: [
      { name: "Virac", zipCodes: ["4800"] },
      { name: "Bagamanoc", zipCodes: ["4801"] },
      { name: "Baras", zipCodes: ["4802"] },
      { name: "Bato", zipCodes: ["4803"] },
      { name: "Caramoran", zipCodes: ["4804"] },
      { name: "Gigmoto", zipCodes: ["4805"] },
      { name: "Pandan", zipCodes: ["4806"] },
      { name: "Panganiban", zipCodes: ["4807"] },
      { name: "San Andres", zipCodes: ["4808"] },
      { name: "San Miguel", zipCodes: ["4809"] },
      { name: "Viga", zipCodes: ["4810"] }
    ]
  },
  {
    name: "Masbate",
    cities: [
      { name: "Masbate City", zipCodes: ["5400"] },
      { name: "Aroroy", zipCodes: ["5401"] },
      { name: "Baleno", zipCodes: ["5402"] },
      { name: "Balud", zipCodes: ["5403"] },
      { name: "Batuan", zipCodes: ["5404"] },
      { name: "Cataingan", zipCodes: ["5405"] },
      { name: "Cawayan", zipCodes: ["5406"] },
      { name: "Claveria", zipCodes: ["5407"] },
      { name: "Dimasalang", zipCodes: ["5408"] },
      { name: "Esperanza", zipCodes: ["5409"] },
      { name: "Mandaon", zipCodes: ["5410"] },
      { name: "Milagros", zipCodes: ["5411"] },
      { name: "Mobo", zipCodes: ["5412"] },
      { name: "Monreal", zipCodes: ["5413"] },
      { name: "Palanas", zipCodes: ["5414"] },
      { name: "Pio V. Corpuz", zipCodes: ["5415"] },
      { name: "Placer", zipCodes: ["5416"] },
      { name: "San Fernando", zipCodes: ["5417"] },
      { name: "San Jacinto", zipCodes: ["5418"] },
      { name: "San Pascual", zipCodes: ["5419"] },
      { name: "Uson", zipCodes: ["5420"] }
    ]
  },
  {
    name: "Sorsogon",
    cities: [
      { name: "Sorsogon City", zipCodes: ["4700"] },
      { name: "Barcelona", zipCodes: ["4711"] },
      { name: "Bulan", zipCodes: ["4706"] },
      { name: "Bulusan", zipCodes: ["4704"] },
      { name: "Casiguran", zipCodes: ["4702"] },
      { name: "Castilla", zipCodes: ["4701"] },
      { name: "Donsol", zipCodes: ["4715"] },
      { name: "Gubat", zipCodes: ["4710"] },
      { name: "Irosin", zipCodes: ["4707"] },
      { name: "Juban", zipCodes: ["4703"] },
      { name: "Magallanes", zipCodes: ["4705"] },
      { name: "Matnog", zipCodes: ["4708"] },
      { name: "Pilar", zipCodes: ["4714"] },
      { name: "Prieto Diaz", zipCodes: ["4709"] },
      { name: "Santa Magdalena", zipCodes: ["4712"] }
    ]
  },

  // VISAYAS
  // Region VI (Western Visayas)
  {
    name: "Aklan",
    cities: [
      { name: "Kalibo", zipCodes: ["5600"] },
      { name: "Altavas", zipCodes: ["5601"] },
      { name: "Balete", zipCodes: ["5602"] },
      { name: "Banga", zipCodes: ["5603"] },
      { name: "Batan", zipCodes: ["5604"] },
      { name: "Buruanga", zipCodes: ["5605"] },
      { name: "Ibajay", zipCodes: ["5606"] },
      { name: "Lezo", zipCodes: ["5607"] },
      { name: "Libacao", zipCodes: ["5608"] },
      { name: "Madalag", zipCodes: ["5609"] },
      { name: "Makato", zipCodes: ["5610"] },
      { name: "Malay", zipCodes: ["5608"] },
      { name: "Malinao", zipCodes: ["5611"] },
      { name: "Nabas", zipCodes: ["5612"] },
      { name: "New Washington", zipCodes: ["5613"] },
      { name: "Numancia", zipCodes: ["5614"] },
      { name: "Tangalan", zipCodes: ["5615"] }
    ]
  },
  {
    name: "Antique",
    cities: [
      { name: "San Jose de Buenavista", zipCodes: ["5700"] },
      { name: "Anini-y", zipCodes: ["5701"] },
      { name: "Barbaza", zipCodes: ["5702"] },
      { name: "Belison", zipCodes: ["5703"] },
      { name: "Bugasong", zipCodes: ["5704"] },
      { name: "Caluya", zipCodes: ["5705"] },
      { name: "Culasi", zipCodes: ["5706"] },
      { name: "Hamtic", zipCodes: ["5707"] },
      { name: "Laua-an", zipCodes: ["5708"] },
      { name: "Libertad", zipCodes: ["5709"] },
      { name: "Pandan", zipCodes: ["5710"] },
      { name: "Patnongon", zipCodes: ["5711"] },
      { name: "San Remigio", zipCodes: ["5712"] },
      { name: "Sebaste", zipCodes: ["5713"] },
      { name: "Sibalom", zipCodes: ["5714"] },
      { name: "Tibiao", zipCodes: ["5715"] },
      { name: "Tobias Fornier", zipCodes: ["5716"] },
      { name: "Valderrama", zipCodes: ["5717"] }
    ]
  },
  {
    name: "Capiz",
    cities: [
      { name: "Roxas City", zipCodes: ["5800"] },
      { name: "Cuartero", zipCodes: ["5801"] },
      { name: "Dao", zipCodes: ["5802"] },
      { name: "Dumalag", zipCodes: ["5803"] },
      { name: "Dumarao", zipCodes: ["5804"] },
      { name: "Ivisan", zipCodes: ["5805"] },
      { name: "Jamindan", zipCodes: ["5806"] },
      { name: "Ma-ayon", zipCodes: ["5807"] },
      { name: "Mambusao", zipCodes: ["5808"] },
      { name: "Panay", zipCodes: ["5809"] },
      { name: "Panitan", zipCodes: ["5810"] },
      { name: "Pilar", zipCodes: ["5811"] },
      { name: "Pontevedra", zipCodes: ["5812"] },
      { name: "President Roxas", zipCodes: ["5813"] },
      { name: "Sapi-an", zipCodes: ["5814"] },
      { name: "Sigma", zipCodes: ["5815"] },
      { name: "Tapaz", zipCodes: ["5816"] }
    ]
  },
  {
    name: "Guimaras",
    cities: [
      { name: "Jordan", zipCodes: ["5045"] },
      { name: "Buenavista", zipCodes: ["5040"] },
      { name: "Nueva Valencia", zipCodes: ["5041"] },
      { name: "San Lorenzo", zipCodes: ["5042"] },
      { name: "Sibunag", zipCodes: ["5043"] }
    ]
  },
  {
    name: "Iloilo",
    cities: [
      { name: "Iloilo City", zipCodes: ["5000"] },
      { name: "Passi City", zipCodes: ["5037"] },
      { name: "Ajuy", zipCodes: ["5001"] },
      { name: "Alimodian", zipCodes: ["5002"] },
      { name: "Anilao", zipCodes: ["5003"] },
      { name: "Badiangan", zipCodes: ["5004"] },
      { name: "Balasan", zipCodes: ["5005"] },
      { name: "Banate", zipCodes: ["5006"] },
      { name: "Barotac Nuevo", zipCodes: ["5007"] },
      { name: "Barotac Viejo", zipCodes: ["5008"] },
      { name: "Batad", zipCodes: ["5009"] },
      { name: "Bingawan", zipCodes: ["5010"] },
      { name: "Cabatuan", zipCodes: ["5011"] },
      { name: "Calinog", zipCodes: ["5012"] },
      { name: "Carles", zipCodes: ["5013"] },
      { name: "Concepcion", zipCodes: ["5014"] },
      { name: "Dingle", zipCodes: ["5015"] },
      { name: "Dueñas", zipCodes: ["5016"] },
      { name: "Dumangas", zipCodes: ["5017"] },
      { name: "Estancia", zipCodes: ["5018"] },
      { name: "Guimbal", zipCodes: ["5019"] },
      { name: "Igbaras", zipCodes: ["5020"] },
      { name: "Janiuay", zipCodes: ["5021"] },
      { name: "Lambunao", zipCodes: ["5022"] },
      { name: "Leganes", zipCodes: ["5023"] },
      { name: "Lemery", zipCodes: ["5024"] },
      { name: "Leon", zipCodes: ["5025"] },
      { name: "Maasin", zipCodes: ["5026"] },
      { name: "Miagao", zipCodes: ["5027"] },
      { name: "Mina", zipCodes: ["5028"] },
      { name: "New Lucena", zipCodes: ["5029"] },
      { name: "Oton", zipCodes: ["5030"] },
      { name: "Pavia", zipCodes: ["5031"] },
      { name: "Pototan", zipCodes: ["5032"] },
      { name: "San Dionisio", zipCodes: ["5033"] },
      { name: "San Enrique", zipCodes: ["5034"] },
      { name: "San Joaquin", zipCodes: ["5035"] },
      { name: "San Miguel", zipCodes: ["5036"] },
      { name: "San Rafael", zipCodes: ["5038"] },
      { name: "Santa Barbara", zipCodes: ["5039"] },
      { name: "Sara", zipCodes: ["5044"] },
      { name: "Tigbauan", zipCodes: ["5046"] },
      { name: "Tubungan", zipCodes: ["5047"] },
      { name: "Zarraga", zipCodes: ["5048"] }
    ]
  },
  {
    name: "Negros Occidental",
    cities: [
      { name: "Bacolod City", zipCodes: ["6100"] },
      { name: "Bago City", zipCodes: ["6101"] },
      { name: "Cadiz City", zipCodes: ["6121"] },
      { name: "Escalante City", zipCodes: ["6124"] },
      { name: "Himamaylan City", zipCodes: ["6108"] },
      { name: "Kabankalan City", zipCodes: ["6111"] },
      { name: "La Carlota City", zipCodes: ["6130"] },
      { name: "Sagay City", zipCodes: ["6122"] },
      { name: "San Carlos City", zipCodes: ["6127"] },
      { name: "Silay City", zipCodes: ["6116"] },
      { name: "Sipalay City", zipCodes: ["6113"] },
      { name: "Talisay City", zipCodes: ["6115"] },
      { name: "Victorias City", zipCodes: ["6119"] },
      { name: "Binalbagan", zipCodes: ["6107"] },
      { name: "Calatrava", zipCodes: ["6126"] },
      { name: "Candoni", zipCodes: ["6110"] },
      { name: "Cauayan", zipCodes: ["6112"] },
      { name: "Enrique B. Magalona", zipCodes: ["6118"] },
      { name: "Hinigaran", zipCodes: ["6106"] },
      { name: "Hinoba-an", zipCodes: ["6114"] },
      { name: "Ilog", zipCodes: ["6109"] },
      { name: "Isabela", zipCodes: ["6128"] },
      { name: "La Castellana", zipCodes: ["6131"] },
      { name: "Manapla", zipCodes: ["6120"] },
      { name: "Moises Padilla", zipCodes: ["6132"] },
      { name: "Murcia", zipCodes: ["6129"] },
      { name: "Pontevedra", zipCodes: ["6105"] },
      { name: "Pulupandan", zipCodes: ["6104"] },
      { name: "Salvador Benedicto", zipCodes: ["6133"] },
      { name: "San Enrique", zipCodes: ["6103"] },
      { name: "Toboso", zipCodes: ["6123"] },
      { name: "Valladolid", zipCodes: ["6102"] }
    ]
  },

  // Region VII (Central Visayas)
  {
    name: "Bohol",
    cities: [
      { name: "Tagbilaran City", zipCodes: ["6300"] },
      { name: "Alburquerque", zipCodes: ["6301"] },
      { name: "Alicia", zipCodes: ["6302"] },
      { name: "Anda", zipCodes: ["6303"] },
      { name: "Antequera", zipCodes: ["6304"] },
      { name: "Baclayon", zipCodes: ["6305"] },
      { name: "Balilihan", zipCodes: ["6306"] },
      { name: "Batuan", zipCodes: ["6307"] },
      { name: "Bien Unido", zipCodes: ["6308"] },
      { name: "Bilar", zipCodes: ["6309"] },
      { name: "Buenavista", zipCodes: ["6310"] },
      { name: "Calape", zipCodes: ["6311"] },
      { name: "Candijay", zipCodes: ["6312"] },
      { name: "Carmen", zipCodes: ["6313"] },
      { name: "Catigbian", zipCodes: ["6314"] },
      { name: "Clarin", zipCodes: ["6315"] },
      { name: "Corella", zipCodes: ["6316"] },
      { name: "Cortes", zipCodes: ["6317"] },
      { name: "Dagohoy", zipCodes: ["6318"] },
      { name: "Danao", zipCodes: ["6319"] },
      { name: "Dauis", zipCodes: ["6320"] },
      { name: "Dimiao", zipCodes: ["6321"] },
      { name: "Duero", zipCodes: ["6322"] },
      { name: "Garcia Hernandez", zipCodes: ["6323"] },
      { name: "Getafe", zipCodes: ["6324"] },
      { name: "Guindulman", zipCodes: ["6325"] },
      { name: "Inabanga", zipCodes: ["6326"] },
      { name: "Jagna", zipCodes: ["6327"] },
      { name: "Jetafe", zipCodes: ["6328"] },
      { name: "Lila", zipCodes: ["6329"] },
      { name: "Loay", zipCodes: ["6330"] },
      { name: "Loboc", zipCodes: ["6331"] },
      { name: "Loon", zipCodes: ["6332"] },
      { name: "Mabini", zipCodes: ["6333"] },
      { name: "Maribojoc", zipCodes: ["6334"] },
      { name: "Panglao", zipCodes: ["6340"] },
      { name: "Pilar", zipCodes: ["6335"] },
      { name: "President Carlos P. Garcia", zipCodes: ["6336"] },
      { name: "Sagbayan", zipCodes: ["6337"] },
      { name: "San Isidro", zipCodes: ["6338"] },
      { name: "San Miguel", zipCodes: ["6339"] },
      { name: "Sevilla", zipCodes: ["6341"] },
      { name: "Sierra Bullones", zipCodes: ["6342"] },
      { name: "Sikatuna", zipCodes: ["6343"] },
      { name: "Talibon", zipCodes: ["6344"] },
      { name: "Trinidad", zipCodes: ["6345"] },
      { name: "Tubigon", zipCodes: ["6346"] },
      { name: "Ubay", zipCodes: ["6347"] },
      { name: "Valencia", zipCodes: ["6348"] }
    ]
  },
  {
    name: "Cebu",
    cities: [
      { name: "Cebu City", zipCodes: ["6000"] },
      { name: "Bogo City", zipCodes: ["6010"] },
      { name: "Carcar City", zipCodes: ["6019"] },
      { name: "Danao City", zipCodes: ["6004"] },
      { name: "Lapu-Lapu City", zipCodes: ["6015"] },
      { name: "Mandaue City", zipCodes: ["6014"] },
      { name: "Naga City", zipCodes: ["6037"] },
      { name: "Talisay City", zipCodes: ["6045"] },
      { name: "Toledo City", zipCodes: ["6038"] },
      { name: "Alcantara", zipCodes: ["6033"] },
      { name: "Alcoy", zipCodes: ["6021"] },
      { name: "Alegria", zipCodes: ["6030"] },
      { name: "Aloguinsan", zipCodes: ["6020"] },
      { name: "Argao", zipCodes: ["6021"] },
      { name: "Asturias", zipCodes: ["6042"] },
      { name: "Badian", zipCodes: ["6031"] },
      { name: "Balamban", zipCodes: ["6041"] },
      { name: "Bantayan", zipCodes: ["6052"] },
      { name: "Barili", zipCodes: ["6036"] },
      { name: "Boljoon", zipCodes: ["6024"] },
      { name: "Borbon", zipCodes: ["6008"] },
      { name: "Carmen", zipCodes: ["6005"] },
      { name: "Catmon", zipCodes: ["6006"] },
      { name: "Compostela", zipCodes: ["6003"] },
      { name: "Consolacion", zipCodes: ["6001"] },
      { name: "Cordova", zipCodes: ["6017"] },
      { name: "Daanbantayan", zipCodes: ["6013"] },
      { name: "Dalaguete", zipCodes: ["6022"] },
      { name: "Dumanjug", zipCodes: ["6035"] },
      { name: "Ginatilan", zipCodes: ["6032"] },
      { name: "Liloan", zipCodes: ["6002"] },
      { name: "Madridejos", zipCodes: ["6053"] },
      { name: "Malabuyoc", zipCodes: ["6029"] },
      { name: "Medellin", zipCodes: ["6012"] },
      { name: "Minglanilla", zipCodes: ["6046"] },
      { name: "Moalboal", zipCodes: ["6032"] },
      { name: "Oslob", zipCodes: ["6025"] },
      { name: "Pilar", zipCodes: ["6039"] },
      { name: "Pinamungajan", zipCodes: ["6040"] },
      { name: "Poro", zipCodes: ["6049"] },
      { name: "Ronda", zipCodes: ["6034"] },
      { name: "Samboan", zipCodes: ["6027"] },
      { name: "San Fernando", zipCodes: ["6018"] },
      { name: "San Francisco", zipCodes: ["6050"] },
      { name: "San Remigio", zipCodes: ["6011"] },
      { name: "Santa Fe", zipCodes: ["6047"] },
      { name: "Santander", zipCodes: ["6026"] },
      { name: "Sibonga", zipCodes: ["6023"] },
      { name: "Sogod", zipCodes: ["6007"] },
      { name: "Tabogon", zipCodes: ["6009"] },
      { name: "Tabuelan", zipCodes: ["6043"] },
      { name: "Tuburan", zipCodes: ["6044"] },
      { name: "Tudela", zipCodes: ["6051"] }
    ]
  },
  {
    name: "Negros Oriental",
    cities: [
      { name: "Dumaguete City", zipCodes: ["6200"] },
      { name: "Bais City", zipCodes: ["6206"] },
      { name: "Bayawan City", zipCodes: ["6221"] },
      { name: "Canlaon City", zipCodes: ["6223"] },
      { name: "Guihulngan City", zipCodes: ["6214"] },
      { name: "Tanjay City", zipCodes: ["6204"] },
      { name: "Amlan", zipCodes: ["6201"] },
      { name: "Ayungon", zipCodes: ["6222"] },
      { name: "Bacong", zipCodes: ["6216"] },
      { name: "Basay", zipCodes: ["6224"] },
      { name: "Bindoy", zipCodes: ["6207"] },
      { name: "Dauin", zipCodes: ["6217"] },
      { name: "Jimalalud", zipCodes: ["6215"] },
      { name: "La Libertad", zipCodes: ["6213"] },
      { name: "Mabinay", zipCodes: ["6225"] },
      { name: "Manjuyod", zipCodes: ["6205"] },
      { name: "Pamplona", zipCodes: ["6202"] },
      { name: "San Jose", zipCodes: ["6212"] },
      { name: "Santa Catalina", zipCodes: ["6226"] },
      { name: "Siaton", zipCodes: ["6218"] },
      { name: "Sibulan", zipCodes: ["6219"] },
      { name: "Tayasan", zipCodes: ["6203"] },
      { name: "Valencia", zipCodes: ["6220"] },
      { name: "Vallehermoso", zipCodes: ["6211"] },
      { name: "Zamboanguita", zipCodes: ["6227"] }
    ]
  },
  {
    name: "Siquijor",
    cities: [
      { name: "Siquijor", zipCodes: ["6226"] },
      { name: "Enrique Villanueva", zipCodes: ["6227"] },
      { name: "Larena", zipCodes: ["6228"] },
      { name: "Lazi", zipCodes: ["6229"] },
      { name: "Maria", zipCodes: ["6230"] },
      { name: "San Juan", zipCodes: ["6231"] }
    ]
  },

  // Region VIII (Eastern Visayas)
  {
    name: "Biliran",
    cities: [
      { name: "Naval", zipCodes: ["6560"] },
      { name: "Almeria", zipCodes: ["6561"] },
      { name: "Biliran", zipCodes: ["6562"] },
      { name: "Cabucgayan", zipCodes: ["6563"] },
      { name: "Caibiran", zipCodes: ["6564"] },
      { name: "Culaba", zipCodes: ["6565"] },
      { name: "Kawayan", zipCodes: ["6566"] },
      { name: "Maripipi", zipCodes: ["6567"] }
    ]
  },
  {
    name: "Eastern Samar",
    cities: [
      { name: "Borongan City", zipCodes: ["6800"] },
      { name: "Arteche", zipCodes: ["6807"] },
      { name: "Balangiga", zipCodes: ["6812"] },
      { name: "Balangkayan", zipCodes: ["6813"] },
      { name: "Can-avid", zipCodes: ["6804"] },
      { name: "Dolores", zipCodes: ["6805"] },
      { name: "General MacArthur", zipCodes: ["6814"] },
      { name: "Giporlos", zipCodes: ["6815"] },
      { name: "Guiuan", zipCodes: ["6809"] },
      { name: "Hernani", zipCodes: ["6816"] },
      { name: "Jipapad", zipCodes: ["6806"] },
      { name: "Lawaan", zipCodes: ["6817"] },
      { name: "Llorente", zipCodes: ["6801"] },
      { name: "Maslog", zipCodes: ["6802"] },
      { name: "Maydolong", zipCodes: ["6803"] },
      { name: "Mercedes", zipCodes: ["6818"] },
      { name: "Oras", zipCodes: ["6808"] },
      { name: "Quinapondan", zipCodes: ["6819"] },
      { name: "Salcedo", zipCodes: ["6810"] },
      { name: "San Julian", zipCodes: ["6820"] },
      { name: "San Policarpo", zipCodes: ["6821"] },
      { name: "Sulat", zipCodes: ["6811"] },
      { name: "Taft", zipCodes: ["6822"] }
    ]
  },
  {
    name: "Leyte",
    cities: [
      { name: "Tacloban City", zipCodes: ["6500"] },
      { name: "Ormoc City", zipCodes: ["6541"] },
      { name: "Baybay City", zipCodes: ["6521"] },
      { name: "Abuyog", zipCodes: ["6510"] },
      { name: "Alangalang", zipCodes: ["6516"] },
      { name: "Albuera", zipCodes: ["6542"] },
      { name: "Babatngon", zipCodes: ["6517"] },
      { name: "Bato", zipCodes: ["6511"] },
      { name: "Burauen", zipCodes: ["6518"] },
      { name: "Calubian", zipCodes: ["6519"] },
      { name: "Capoocan", zipCodes: ["6520"] },
      { name: "Carigara", zipCodes: ["6515"] },
      { name: "Dagami", zipCodes: ["6522"] },
      { name: "Dulag", zipCodes: ["6505"] },
      { name: "Hilongos", zipCodes: ["6524"] },
      { name: "Hindang", zipCodes: ["6525"] },
      { name: "Inopacan", zipCodes: ["6526"] },
      { name: "Isabel", zipCodes: ["6527"] },
      { name: "Jaro", zipCodes: ["6528"] },
      { name: "Javier", zipCodes: ["6512"] },
      { name: "Julita", zipCodes: ["6506"] },
      { name: "Kananga", zipCodes: ["6543"] },
      { name: "La Paz", zipCodes: ["6529"] },
      { name: "Leyte", zipCodes: ["6530"] },
      { name: "MacArthur", zipCodes: ["6513"] },
      { name: "Mahaplag", zipCodes: ["6507"] },
      { name: "Matag-ob", zipCodes: ["6544"] },
      { name: "Matalom", zipCodes: ["6531"] },
      { name: "Mayorga", zipCodes: ["6508"] },
      { name: "Merida", zipCodes: ["6545"] },
      { name: "Palo", zipCodes: ["6501"] },
      { name: "Palompon", zipCodes: ["6532"] },
      { name: "Pastrana", zipCodes: ["6502"] },
      { name: "San Isidro", zipCodes: ["6533"] },
      { name: "San Miguel", zipCodes: ["6514"] },
      { name: "Santa Fe", zipCodes: ["6534"] },
      { name: "Tabango", zipCodes: ["6535"] },
      { name: "Tabontabon", zipCodes: ["6509"] },
      { name: "Tanauan", zipCodes: ["6503"] },
      { name: "Tolosa", zipCodes: ["6504"] },
      { name: "Tunga", zipCodes: ["6536"] },
      { name: "Villaba", zipCodes: ["6537"] }
    ]
  },
  {
    name: "Northern Samar",
    cities: [
      { name: "Catarman", zipCodes: ["6400"] },
      { name: "Allen", zipCodes: ["6405"] },
      { name: "Biri", zipCodes: ["6406"] },
      { name: "Bobon", zipCodes: ["6407"] },
      { name: "Capul", zipCodes: ["6408"] },
      { name: "Catubig", zipCodes: ["6409"] },
      { name: "Gamay", zipCodes: ["6410"] },
      { name: "Laoang", zipCodes: ["6411"] },
      { name: "Las Navas", zipCodes: ["6412"] },
      { name: "Lavezares", zipCodes: ["6413"] },
      { name: "Lope de Vega", zipCodes: ["6414"] },
      { name: "Mapanas", zipCodes: ["6415"] },
      { name: "Mondragon", zipCodes: ["6416"] },
      { name: "Palapag", zipCodes: ["6417"] },
      { name: "Pambujan", zipCodes: ["6418"] },
      { name: "Rosario", zipCodes: ["6419"] },
      { name: "San Antonio", zipCodes: ["6420"] },
      { name: "San Isidro", zipCodes: ["6421"] },
      { name: "San Jose", zipCodes: ["6422"] },
      { name: "San Roque", zipCodes: ["6423"] },
      { name: "San Vicente", zipCodes: ["6424"] },
      { name: "Silvino Lobos", zipCodes: ["6425"] },
      { name: "Victoria", zipCodes: ["6426"] }
    ]
  },
  {
    name: "Samar",
    cities: [
      { name: "Catbalogan City", zipCodes: ["6700"] },
      { name: "Calbayog City", zipCodes: ["6710"] },
      { name: "Almagro", zipCodes: ["6701"] },
      { name: "Basey", zipCodes: ["6720"] },
      { name: "Calbiga", zipCodes: ["6721"] },
      { name: "Daram", zipCodes: ["6722"] },
      { name: "Gandara", zipCodes: ["6702"] },
      { name: "Hinabangan", zipCodes: ["6711"] },
      { name: "Jiabong", zipCodes: ["6723"] },
      { name: "Marabut", zipCodes: ["6724"] },
      { name: "Matuguinao", zipCodes: ["6703"] },
      { name: "Motiong", zipCodes: ["6704"] },
      { name: "Pinabacdao", zipCodes: ["6725"] },
      { name: "San Jorge", zipCodes: ["6705"] },
      { name: "San Jose de Buan", zipCodes: ["6712"] },
      { name: "San Sebastian", zipCodes: ["6726"] },
      { name: "Santa Margarita", zipCodes: ["6706"] },
      { name: "Santa Rita", zipCodes: ["6713"] },
      { name: "Santo Niño", zipCodes: ["6714"] },
      { name: "Tagapul-an", zipCodes: ["6715"] },
      { name: "Talalora", zipCodes: ["6707"] },
      { name: "Tarangnan", zipCodes: ["6708"] },
      { name: "Villareal", zipCodes: ["6727"] },
      { name: "Zumarraga", zipCodes: ["6716"] }
    ]
  },
  {
    name: "Southern Leyte",
    cities: [
      { name: "Maasin City", zipCodes: ["6600"] },
      { name: "Anahawan", zipCodes: ["6601"] },
      { name: "Bontoc", zipCodes: ["6602"] },
      { name: "Hinunangan", zipCodes: ["6603"] },
      { name: "Hinundayan", zipCodes: ["6604"] },
      { name: "Libagon", zipCodes: ["6605"] },
      { name: "Liloan", zipCodes: ["6606"] },
      { name: "Macrohon", zipCodes: ["6607"] },
      { name: "Malitbog", zipCodes: ["6608"] },
      { name: "Padre Burgos", zipCodes: ["6609"] },
      { name: "Pintuyan", zipCodes: ["6610"] },
      { name: "Saint Bernard", zipCodes: ["6611"] },
      { name: "San Francisco", zipCodes: ["6612"] },
      { name: "San Juan", zipCodes: ["6613"] },
      { name: "San Ricardo", zipCodes: ["6614"] },
      { name: "Silago", zipCodes: ["6615"] },
      { name: "Sogod", zipCodes: ["6616"] },
      { name: "Tomas Oppus", zipCodes: ["6617"] }
    ]
  },

  // MINDANAO
  // Region IX (Zamboanga Peninsula)
  {
    name: "Zamboanga del Norte",
    cities: [
      { name: "Dipolog City", zipCodes: ["7100"] },
      { name: "Dapitan City", zipCodes: ["7101"] },
      { name: "Bacungan", zipCodes: ["7102"] },
      { name: "Baliguian", zipCodes: ["7103"] },
      { name: "Godod", zipCodes: ["7104"] },
      { name: "Gutalac", zipCodes: ["7105"] },
      { name: "Jose Dalman", zipCodes: ["7106"] },
      { name: "Kalawit", zipCodes: ["7107"] },
      { name: "Katipunan", zipCodes: ["7108"] },
      { name: "La Libertad", zipCodes: ["7109"] },
      { name: "Labason", zipCodes: ["7110"] },
      { name: "Leon B. Postigo", zipCodes: ["7111"] },
      { name: "Liloy", zipCodes: ["7112"] },
      { name: "Manukan", zipCodes: ["7113"] },
      { name: "Mutia", zipCodes: ["7114"] },
      { name: "Piñan", zipCodes: ["7115"] },
      { name: "Polanco", zipCodes: ["7116"] },
      { name: "Pres. Manuel A. Roxas", zipCodes: ["7117"] },
      { name: "Rizal", zipCodes: ["7118"] },
      { name: "Salug", zipCodes: ["7119"] },
      { name: "Sergio Osmeña Sr.", zipCodes: ["7120"] },
      { name: "Siayan", zipCodes: ["7121"] },
      { name: "Sibuco", zipCodes: ["7122"] },
      { name: "Sibutad", zipCodes: ["7123"] },
      { name: "Sindangan", zipCodes: ["7124"] },
      { name: "Siocon", zipCodes: ["7125"] },
      { name: "Sirawai", zipCodes: ["7126"] },
      { name: "Tampilisan", zipCodes: ["7127"] }
    ]
  },
  {
    name: "Zamboanga del Sur",
    cities: [
      { name: "Pagadian City", zipCodes: ["7016"] },
      { name: "Zamboanga City", zipCodes: ["7000"] },
      { name: "Aurora", zipCodes: ["7020"] },
      { name: "Bayog", zipCodes: ["7007"] },
      { name: "Dimataling", zipCodes: ["7021"] },
      { name: "Dinas", zipCodes: ["7022"] },
      { name: "Dumalinao", zipCodes: ["7008"] },
      { name: "Dumingag", zipCodes: ["7009"] },
      { name: "Guipos", zipCodes: ["7023"] },
      { name: "Josefina", zipCodes: ["7010"] },
      { name: "Kumalarang", zipCodes: ["7011"] },
      { name: "Labangan", zipCodes: ["7024"] },
      { name: "Lakewood", zipCodes: ["7017"] },
      { name: "Lapuyan", zipCodes: ["7025"] },
      { name: "Mahayag", zipCodes: ["7026"] },
      { name: "Margosatubig", zipCodes: ["7027"] },
      { name: "Midsalip", zipCodes: ["7028"] },
      { name: "Molave", zipCodes: ["7012"] },
      { name: "Pitogo", zipCodes: ["7029"] },
      { name: "Ramon Magsaysay", zipCodes: ["7013"] },
      { name: "San Miguel", zipCodes: ["7030"] },
      { name: "San Pablo", zipCodes: ["7031"] },
      { name: "Sominot", zipCodes: ["7032"] },
      { name: "Tabina", zipCodes: ["7033"] },
      { name: "Tambulig", zipCodes: ["7014"] },
      { name: "Tigbao", zipCodes: ["7034"] },
      { name: "Tukuran", zipCodes: ["7015"] },
      ]
   },
   {
     name: "Zamboanga Sibugay",
     cities: [
       { name: "Ipil", zipCodes: ["7001"] },
       { name: "Alicia", zipCodes: ["7002"] },
       { name: "Buug", zipCodes: ["7003"] },
       { name: "Diplahan", zipCodes: ["7004"] },
       { name: "Imelda", zipCodes: ["7005"] },
       { name: "Kabasalan", zipCodes: ["7006"] },
       { name: "Mabuhay", zipCodes: ["7018"] },
       { name: "Malangas", zipCodes: ["7019"] },
       { name: "Naga", zipCodes: ["7036"] },
       { name: "Olutanga", zipCodes: ["7037"] },
       { name: "Payao", zipCodes: ["7038"] },
       { name: "Roseller Lim", zipCodes: ["7039"] },
       { name: "Siay", zipCodes: ["7040"] },
       { name: "Talusan", zipCodes: ["7041"] },
       { name: "Titay", zipCodes: ["7042"] },
       { name: "Tungawan", zipCodes: ["7043"] }
     ]
   },

   // Region X (Northern Mindanao)
   {
     name: "Bukidnon",
     cities: [
       { name: "Malaybalay City", zipCodes: ["8700"] },
       { name: "Valencia City", zipCodes: ["8709"] },
       { name: "Baungon", zipCodes: ["8714"] },
       { name: "Cabanglasan", zipCodes: ["8715"] },
       { name: "Damulog", zipCodes: ["8716"] },
       { name: "Dangcagan", zipCodes: ["8717"] },
       { name: "Don Carlos", zipCodes: ["8718"] },
       { name: "Impasugong", zipCodes: ["8719"] },
       { name: "Kadingilan", zipCodes: ["8720"] },
       { name: "Kalilangan", zipCodes: ["8721"] },
       { name: "Kibawe", zipCodes: ["8722"] },
       { name: "Kitaotao", zipCodes: ["8723"] },
       { name: "Lantapan", zipCodes: ["8724"] },
       { name: "Libona", zipCodes: ["8725"] },
       { name: "Malitbog", zipCodes: ["8726"] },
       { name: "Manolo Fortich", zipCodes: ["8703"] },
       { name: "Maramag", zipCodes: ["8727"] },
       { name: "Pangantucan", zipCodes: ["8728"] },
       { name: "Quezon", zipCodes: ["8729"] },
       { name: "San Fernando", zipCodes: ["8730"] },
       { name: "Sumilao", zipCodes: ["8731"] },
       { name: "Talakag", zipCodes: ["8732"] }
     ]
   },
   {
     name: "Camiguin",
     cities: [
       { name: "Mambajao", zipCodes: ["9100"] },
       { name: "Catarman", zipCodes: ["9101"] },
       { name: "Guinsiliban", zipCodes: ["9102"] },
       { name: "Mahinog", zipCodes: ["9103"] },
       { name: "Sagay", zipCodes: ["9104"] }
     ]
   },
   {
     name: "Lanao del Norte",
     cities: [
       { name: "Iligan City", zipCodes: ["9200"] },
       { name: "Bacolod", zipCodes: ["9201"] },
       { name: "Baloi", zipCodes: ["9202"] },
       { name: "Baroy", zipCodes: ["9203"] },
       { name: "Kapatagan", zipCodes: ["9204"] },
       { name: "Kauswagan", zipCodes: ["9205"] },
       { name: "Kolambugan", zipCodes: ["9206"] },
       { name: "Lala", zipCodes: ["9207"] },
       { name: "Linamon", zipCodes: ["9208"] },
       { name: "Magsaysay", zipCodes: ["9209"] },
       { name: "Maigo", zipCodes: ["9210"] },
       { name: "Matungao", zipCodes: ["9211"] },
       { name: "Munai", zipCodes: ["9212"] },
       { name: "Nunungan", zipCodes: ["9213"] },
       { name: "Pantao Ragat", zipCodes: ["9214"] },
       { name: "Pantar", zipCodes: ["9215"] },
       { name: "Poona Piagapo", zipCodes: ["9216"] },
       { name: "Salvador", zipCodes: ["9217"] },
       { name: "Sapad", zipCodes: ["9218"] },
       { name: "Sultan Naga Dimaporo", zipCodes: ["9219"] },
       { name: "Tagoloan", zipCodes: ["9220"] },
       { name: "Tangcal", zipCodes: ["9221"] },
       { name: "Tubod", zipCodes: ["9222"] }
     ]
   },
   {
     name: "Misamis Occidental",
     cities: [
       { name: "Oroquieta City", zipCodes: ["7200"] },
       { name: "Ozamiz City", zipCodes: ["7200"] },
       { name: "Tangub City", zipCodes: ["7214"] },
       { name: "Aloran", zipCodes: ["7201"] },
       { name: "Baliangao", zipCodes: ["7202"] },
       { name: "Bonifacio", zipCodes: ["7203"] },
       { name: "Calamba", zipCodes: ["7204"] },
       { name: "Clarin", zipCodes: ["7205"] },
       { name: "Concepcion", zipCodes: ["7206"] },
       { name: "Don Victoriano Chiongbian", zipCodes: ["7207"] },
       { name: "Jimenez", zipCodes: ["7208"] },
       { name: "Lopez Jaena", zipCodes: ["7209"] },
       { name: "Panaon", zipCodes: ["7210"] },
       { name: "Plaridel", zipCodes: ["7211"] },
       { name: "Sapang Dalaga", zipCodes: ["7212"] },
       { name: "Sinacaban", zipCodes: ["7213"] },
       { name: "Tudela", zipCodes: ["7215"] }
     ]
   },
   {
     name: "Misamis Oriental",
     cities: [
       { name: "Cagayan de Oro City", zipCodes: ["9000"] },
       { name: "Gingoog City", zipCodes: ["9014"] },
       { name: "Alubijid", zipCodes: ["9013"] },
       { name: "Balingasag", zipCodes: ["9005"] },
       { name: "Balingoan", zipCodes: ["9015"] },
       { name: "Binuangan", zipCodes: ["9016"] },
       { name: "Claveria", zipCodes: ["9004"] },
       { name: "El Salvador", zipCodes: ["9003"] },
       { name: "Gitagum", zipCodes: ["9017"] },
       { name: "Initao", zipCodes: ["9022"] },
       { name: "Jasaan", zipCodes: ["9023"] },
       { name: "Kinoguitan", zipCodes: ["9018"] },
       { name: "Lagonglong", zipCodes: ["9019"] },
       { name: "Laguindingan", zipCodes: ["9024"] },
       { name: "Libertad", zipCodes: ["9020"] },
       { name: "Lugait", zipCodes: ["9025"] },
       { name: "Magsaysay", zipCodes: ["9021"] },
       { name: "Manticao", zipCodes: ["9026"] },
       { name: "Medina", zipCodes: ["9027"] },
       { name: "Naawan", zipCodes: ["9023"] },
       { name: "Opol", zipCodes: ["9016"] },
       { name: "Salay", zipCodes: ["9028"] },
       { name: "Sugbongcogon", zipCodes: ["9029"] },
       { name: "Tagoloan", zipCodes: ["9001"] },
       { name: "Talisayan", zipCodes: ["9030"] },
       { name: "Villanueva", zipCodes: ["9002"] }
     ]
   },

   // Region XI (Davao Region)
   {
     name: "Davao de Oro",
     cities: [
       { name: "Nabunturan", zipCodes: ["8800"] },
       { name: "Compostela", zipCodes: ["8803"] },
       { name: "Laak", zipCodes: ["8804"] },
       { name: "Mabini", zipCodes: ["8805"] },
       { name: "Maco", zipCodes: ["8806"] },
       { name: "Maragusan", zipCodes: ["8807"] },
       { name: "Mawab", zipCodes: ["8808"] },
       { name: "Monkayo", zipCodes: ["8809"] },
       { name: "Montevista", zipCodes: ["8810"] },
       { name: "New Bataan", zipCodes: ["8811"] },
       { name: "Pantukan", zipCodes: ["8812"] }
     ]
   },
   {
     name: "Davao del Norte",
     cities: [
       { name: "Tagum City", zipCodes: ["8100"] },
       { name: "Panabo City", zipCodes: ["8105"] },
       { name: "Samal City", zipCodes: ["8119"] },
       { name: "Asuncion", zipCodes: ["8101"] },
       { name: "Braulio E. Dujali", zipCodes: ["8102"] },
       { name: "Carmen", zipCodes: ["8103"] },
       { name: "Kapalong", zipCodes: ["8104"] },
       { name: "New Corella", zipCodes: ["8106"] },
       { name: "San Isidro", zipCodes: ["8107"] },
       { name: "Santo Tomas", zipCodes: ["8108"] },
       { name: "Talaingod", zipCodes: ["8109"] }
     ]
   },
   {
     name: "Davao del Sur",
     cities: [
       { name: "Digos City", zipCodes: ["8002"] },
       { name: "Bansalan", zipCodes: ["8005"] },
       { name: "Don Marcelino", zipCodes: ["8006"] },
       { name: "Hagonoy", zipCodes: ["8007"] },
       { name: "Jose Abad Santos", zipCodes: ["8008"] },
       { name: "Kiblawan", zipCodes: ["8009"] },
       { name: "Magsaysay", zipCodes: ["8010"] },
       { name: "Malalag", zipCodes: ["8011"] },
       { name: "Matanao", zipCodes: ["8003"] },
       { name: "Padada", zipCodes: ["8004"] },
       { name: "Santa Cruz", zipCodes: ["8001"] },
       { name: "Sulop", zipCodes: ["8012"] }
     ]
   },
   {
     name: "Davao Occidental",
     cities: [
       { name: "Malita", zipCodes: ["8016"] },
       { name: "Don Marcelino", zipCodes: ["8017"] },
       { name: "Jose Abad Santos", zipCodes: ["8018"] },
       { name: "Santa Maria", zipCodes: ["8019"] }
     ]
   },
   {
     name: "Davao Oriental",
     cities: [
       { name: "Mati City", zipCodes: ["8200"] },
       { name: "Baganga", zipCodes: ["8201"] },
       { name: "Banaybanay", zipCodes: ["8202"] },
       { name: "Boston", zipCodes: ["8203"] },
       { name: "Caraga", zipCodes: ["8204"] },
       { name: "Cateel", zipCodes: ["8205"] },
       { name: "Governor Generoso", zipCodes: ["8206"] },
       { name: "Lupon", zipCodes: ["8207"] },
       { name: "Manay", zipCodes: ["8208"] },
       { name: "San Isidro", zipCodes: ["8209"] },
       { name: "Tarragona", zipCodes: ["8210"] }
     ]
   },

   // Region XII (SOCCSKSARGEN)
   {
     name: "Cotabato",
     cities: [
       { name: "Kidapawan City", zipCodes: ["9400"] },
       { name: "Alamada", zipCodes: ["9401"] },
       { name: "Aleosan", zipCodes: ["9402"] },
       { name: "Antipas", zipCodes: ["9403"] },
       { name: "Arakan", zipCodes: ["9404"] },
       { name: "Banisilan", zipCodes: ["9405"] },
       { name: "Carmen", zipCodes: ["9406"] },
       { name: "Kabacan", zipCodes: ["9407"] },
       { name: "Libungan", zipCodes: ["9408"] },
       { name: "M'lang", zipCodes: ["9409"] },
       { name: "Magpet", zipCodes: ["9410"] },
       { name: "Makilala", zipCodes: ["9411"] },
       { name: "Matalam", zipCodes: ["9412"] },
       { name: "Midsayap", zipCodes: ["9413"] },
       { name: "Pigcawayan", zipCodes: ["9414"] },
       { name: "Pikit", zipCodes: ["9415"] },
       { name: "President Roxas", zipCodes: ["9416"] },
       { name: "Tulunan", zipCodes: ["9417"] }
     ]
   },
   {
     name: "Sarangani",
     cities: [
       { name: "Alabel", zipCodes: ["9500"] },
       { name: "Glan", zipCodes: ["9501"] },
       { name: "Kiamba", zipCodes: ["9502"] },
       { name: "Maasim", zipCodes: ["9503"] },
       { name: "Maitum", zipCodes: ["9504"] },
       { name: "Malapatan", zipCodes: ["9505"] },
       { name: "Malungon", zipCodes: ["9506"] }
     ]
   },
   {
     name: "South Cotabato",
     cities: [
       { name: "Koronadal City", zipCodes: ["9506"] },
       { name: "General Santos City", zipCodes: ["9500"] },
       { name: "Banga", zipCodes: ["9511"] },
       { name: "Lake Sebu", zipCodes: ["9512"] },
       { name: "Norala", zipCodes: ["9513"] },
       { name: "Polomolok", zipCodes: ["9514"] },
       { name: "Santo Niño", zipCodes: ["9515"] },
       { name: "Surallah", zipCodes: ["9512"] },
       { name: "T'boli", zipCodes: ["9513"] },
       { name: "Tampakan", zipCodes: ["9516"] },
       { name: "Tantangan", zipCodes: ["9517"] },
       { name: "Tupi", zipCodes: ["9518"] }
     ]
   },
   {
     name: "Sultan Kudarat",
     cities: [
       { name: "Isulan", zipCodes: ["9805"] },
       { name: "Tacurong City", zipCodes: ["9800"] },
       { name: "Bagumbayan", zipCodes: ["9801"] },
       { name: "Columbio", zipCodes: ["9802"] },
       { name: "Esperanza", zipCodes: ["9803"] },
       { name: "Kalamansig", zipCodes: ["9804"] },
       { name: "Lambayong", zipCodes: ["9806"] },
       { name: "Lebak", zipCodes: ["9807"] },
       { name: "Lutayan", zipCodes: ["9808"] },
       { name: "Palimbang", zipCodes: ["9809"] },
       { name: "President Quirino", zipCodes: ["9810"] },
       { name: "Senator Ninoy Aquino", zipCodes: ["9811"] }
     ]
   },

   // Region XIII (Caraga)
   {
     name: "Agusan del Norte",
     cities: [
       { name: "Butuan City", zipCodes: ["8600"] },
       { name: "Cabadbaran City", zipCodes: ["8605"] },
       { name: "Buenavista", zipCodes: ["8601"] },
       { name: "Carmen", zipCodes: ["8602"] },
       { name: "Jabonga", zipCodes: ["8603"] },
       { name: "Kitcharao", zipCodes: ["8604"] },
       { name: "Las Nieves", zipCodes: ["8606"] },
       { name: "Magallanes", zipCodes: ["8607"] },
       { name: "Nasipit", zipCodes: ["8608"] },
       { name: "Remedios T. Romualdez", zipCodes: ["8609"] },
       { name: "Santiago", zipCodes: ["8610"] },
       { name: "Tubay", zipCodes: ["8611"] }
     ]
   },
   {
     name: "Agusan del Sur",
     cities: [
       { name: "Bayugan City", zipCodes: ["8502"] },
       { name: "Bunawan", zipCodes: ["8504"] },
       { name: "Esperanza", zipCodes: ["8105"] },
       { name: "La Paz", zipCodes: ["8506"] },
       { name: "Loreto", zipCodes: ["8507"] },
       { name: "Prosperidad", zipCodes: ["8500"] },
       { name: "Rosario", zipCodes: ["8508"] },
       { name: "San Francisco", zipCodes: ["8501"] },
       { name: "San Luis", zipCodes: ["8509"] },
       { name: "Santa Josefa", zipCodes: ["8510"] },
       { name: "Sibagat", zipCodes: ["8511"] },
       { name: "Talacogon", zipCodes: ["8512"] },
       { name: "Trento", zipCodes: ["8513"] },
       { name: "Veruela", zipCodes: ["8514"] }
     ]
   },
   {
     name: "Dinagat Islands",
     cities: [
       { name: "San Jose", zipCodes: ["8411"] },
       { name: "Basilisa", zipCodes: ["8412"] },
       { name: "Cagdianao", zipCodes: ["8413"] },
       { name: "Dinagat", zipCodes: ["8414"] },
       { name: "Libjo", zipCodes: ["8415"] },
       { name: "Loreto", zipCodes: ["8416"] },
       { name: "Tubajon", zipCodes: ["8417"] }
     ]
   },
   {
     name: "Surigao del Norte",
     cities: [
       { name: "Surigao City", zipCodes: ["8400"] },
       { name: "Alegria", zipCodes: ["8401"] },
       { name: "Bacuag", zipCodes: ["8402"] },
       { name: "Burgos", zipCodes: ["8403"] },
       { name: "Claver", zipCodes: ["8404"] },
       { name: "Dapa", zipCodes: ["8405"] },
       { name: "Del Carmen", zipCodes: ["8406"] },
       { name: "General Luna", zipCodes: ["8419"] },
       { name: "Gigaquit", zipCodes: ["8407"] },
       { name: "Mainit", zipCodes: ["8408"] },
       { name: "Malimono", zipCodes: ["8409"] },
       { name: "Pilar", zipCodes: ["8410"] },
       { name: "Placer", zipCodes: ["8418"] },
       { name: "San Benito", zipCodes: ["8420"] },
       { name: "San Francisco", zipCodes: ["8421"] },
       { name: "San Isidro", zipCodes: ["8422"] },
       { name: "Santa Monica", zipCodes: ["8423"] },
       { name: "Sison", zipCodes: ["8424"] },
       { name: "Socorro", zipCodes: ["8425"] },
       { name: "Tagana-an", zipCodes: ["8426"] },
       { name: "Tubod", zipCodes: ["8427"] }
     ]
   },
   {
     name: "Surigao del Sur",
     cities: [
       { name: "Tandag City", zipCodes: ["8300"] },
       { name: "Bislig City", zipCodes: ["8311"] },
       { name: "Barobo", zipCodes: ["8301"] },
       { name: "Bayabas", zipCodes: ["8302"] },
       { name: "Cagwait", zipCodes: ["8303"] },
       { name: "Cantilan", zipCodes: ["8304"] },
       { name: "Carmen", zipCodes: ["8305"] },
       { name: "Carrascal", zipCodes: ["8306"] },
       { name: "Cortes", zipCodes: ["8307"] },
       { name: "Hinatuan", zipCodes: ["8308"] },
       { name: "Lanuza", zipCodes: ["8309"] },
       { name: "Lianga", zipCodes: ["8310"] },
       { name: "Lingig", zipCodes: ["8312"] },
       { name: "Madrid", zipCodes: ["8313"] },
       { name: "Marihatag", zipCodes: ["8314"] },
       { name: "San Agustin", zipCodes: ["8315"] },
       { name: "San Miguel", zipCodes: ["8316"] },
       { name: "Tagbina", zipCodes: ["8317"] },
       { name: "Tago", zipCodes: ["8318"] }
     ]
   },

   // BARMM (Bangsamoro Autonomous Region in Muslim Mindanao)
   {
     name: "Basilan",
     cities: [
       { name: "Isabela City", zipCodes: ["7300"] },
       { name: "Lamitan City", zipCodes: ["7301"] },
       { name: "Akbar", zipCodes: ["7302"] },
       { name: "Al-Barka", zipCodes: ["7303"] },
       { name: "Hadji Mohammad Ajul", zipCodes: ["7304"] },
       { name: "Hadji Muhtamad", zipCodes: ["7305"] },
       { name: "Lantawan", zipCodes: ["7306"] },
       { name: "Maluso", zipCodes: ["7307"] },
       { name: "Sumisip", zipCodes: ["7308"] },
       { name: "Tabuan-Lasa", zipCodes: ["7309"] },
       { name: "Tipo-Tipo", zipCodes: ["7310"] },
       { name: "Tuburan", zipCodes: ["7311"] },
       { name: "Ungkaya Pukan", zipCodes: ["7312"] }
     ]
   },
   {
     name: "Lanao del Sur",
     cities: [
       { name: "Marawi City", zipCodes: ["9700"] },
       { name: "Amai Manabilang", zipCodes: ["9701"] },
       { name: "Bacolod-Kalawi", zipCodes: ["9702"] },
       { name: "Balabagan", zipCodes: ["9703"] },
       { name: "Balindong", zipCodes: ["9704"] },
       { name: "Bayang", zipCodes: ["9705"] },
       { name: "Binidayan", zipCodes: ["9706"] },
       { name: "Buadiposo-Buntong", zipCodes: ["9707"] },
       { name: "Bubong", zipCodes: ["9708"] },
       { name: "Butig", zipCodes: ["9709"] },
       { name: "Ganassi", zipCodes: ["9710"] },
       { name: "Kapai", zipCodes: ["9711"] },
       { name: "Lumba-Bayabao", zipCodes: ["9712"] },
       { name: "Lumbaca-Unayan", zipCodes: ["9713"] },
       { name: "Lumbatan", zipCodes: ["9714"] },
       { name: "Lumbayanague", zipCodes: ["9715"] },
       { name: "Madalum", zipCodes: ["9716"] },
       { name: "Madamba", zipCodes: ["9717"] },
       { name: "Maguing", zipCodes: ["9718"] },
       { name: "Malabang", zipCodes: ["9719"] },
       { name: "Marantao", zipCodes: ["9720"] },
       { name: "Marogong", zipCodes: ["9721"] },
       { name: "Masiu", zipCodes: ["9722"] },
       { name: "Mulondo", zipCodes: ["9723"] },
       { name: "Pagayawan", zipCodes: ["9724"] },
       { name: "Piagapo", zipCodes: ["9725"] },
       { name: "Poona Bayabao", zipCodes: ["9726"] },
       { name: "Pualas", zipCodes: ["9727"] },
       { name: "Saguiaran", zipCodes: ["9728"] },
       { name: "Sultan Dumalondong", zipCodes: ["9729"] },
       { name: "Tagoloan II", zipCodes: ["9730"] },
       { name: "Tamparan", zipCodes: ["9731"] },
       { name: "Taraka", zipCodes: ["9732"] },
       { name: "Tubaran", zipCodes: ["9733"] },
       { name: "Tugaya", zipCodes: ["9734"] },
       { name: "Wao", zipCodes: ["9735"] }
     ]
   },
   {
     name: "Maguindanao del Norte",
     cities: [
       { name: "Datu Odin Sinsuat", zipCodes: ["9601"] },
       { name: "Kabuntalan", zipCodes: ["9602"] },
       { name: "Matanog", zipCodes: ["9603"] },
       { name: "Northern Kabuntalan", zipCodes: ["9604"] },
       { name: "Parang", zipCodes: ["9605"] },
       { name: "Sultan Kudarat", zipCodes: ["9606"] },
       { name: "Sultan Mastura", zipCodes: ["9607"] }
     ]
   },
   {
     name: "Maguindanao del Sur",
     cities: [
       { name: "Buluan", zipCodes: ["9608"] },
       { name: "Gen. S. K. Pendatun", zipCodes: ["9609"] },
       { name: "Guindulungan", zipCodes: ["9610"] },
       { name: "Pagalungan", zipCodes: ["9611"] },
       { name: "Paglat", zipCodes: ["9612"] },
       { name: "Pandag", zipCodes: ["9613"] },
       { name: "Rajah Buayan", zipCodes: ["9614"] },
       { name: "South Upi", zipCodes: ["9615"] },
       { name: "Sultan sa Barongis", zipCodes: ["9616"] },
       { name: "Talayan", zipCodes: ["9617"] },
       { name: "Talitay", zipCodes: ["9618"] }
     ]
   },
   {
     name: "Sulu",
     cities: [
       { name: "Jolo", zipCodes: ["7400"] },
       { name: "Banguingui", zipCodes: ["7401"] },
       { name: "Hadji Panglima Tahil", zipCodes: ["7402"] },
       { name: "Indanan", zipCodes: ["7403"] },
       { name: "Kalingalan Caluang", zipCodes: ["7404"] },
       { name: "Lugus", zipCodes: ["7405"] },
       { name: "Luuk", zipCodes: ["7406"] },
       { name: "Maimbung", zipCodes: ["7407"] },
       { name: "Old Panamao", zipCodes: ["7408"] },
       { name: "Omar", zipCodes: ["7409"] },
       { name: "Pandami", zipCodes: ["7410"] },
       { name: "Panglima Estino", zipCodes: ["7411"] },
       { name: "Pangutaran", zipCodes: ["7412"] },
       { name: "Parang", zipCodes: ["7413"] },
       { name: "Pata", zipCodes: ["7414"] },
       { name: "Patikul", zipCodes: ["7415"] },
       { name: "Siasi", zipCodes: ["7416"] },
       { name: "Talipao", zipCodes: ["7417"] },
       { name: "Tapul", zipCodes: ["7418"] }
     ]
   },
   {
     name: "Tawi-Tawi",
     cities: [
       { name: "Bongao", zipCodes: ["7500"] },
       { name: "Languyan", zipCodes: ["7501"] },
       { name: "Mapun", zipCodes: ["7502"] },
       { name: "Panglima Sugala", zipCodes: ["7503"] },
       { name: "Sapa-Sapa", zipCodes: ["7504"] },
       { name: "Sibutu", zipCodes: ["7505"] },
       { name: "Simunul", zipCodes: ["7506"] },
       { name: "Sitangkai", zipCodes: ["7507"] },
       { name: "South Ubian", zipCodes: ["7508"] },
       { name: "Tandubas", zipCodes: ["7509"] },
       { name: "Turtle Islands", zipCodes: ["7510"] }
     ]
   }
 ];

export function getProvinceNames(): string[] {
  return philippinesLocations.map(province => province.name);
}

export function getCitiesForProvince(provinceName: string): City[] {
  const province = philippinesLocations.find(p => p.name.toLowerCase() === provinceName.toLowerCase());
  return province ? province.cities : [];
}